### ISSUE TITLE
Cast: Custom element doesnt exist: hui-section-row

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#101]
My Home Assistant version: 0.109.6

manual resources config:
```
- url: /local/lovelace/resources/lovelace-fold-entity-row/fold-entity-row.js?v=16
  type: module
```

My lovelace configuration method (GUI or yaml): Yaml

What I am doing:
casting a card

What I expected to happen:
to show properly like:

<img width="378" alt="Schermafbeelding 2020-05-13 om 23 38 31" src="https://user-images.githubusercontent.com/33354141/81868840-46cf7480-9573-11ea-8c81-b302b01ddb75.png">

What happened instead:

![20200513_213741789_iOS](https://user-images.githubusercontent.com/33354141/81869012-957d0e80-9573-11ea-9dc5-af5003e86617.jpg)

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

type: entities
title: Darksky Forecast
entities:
  - entity: sensor.dark_sky_forecast_overnight_low_temperature_0d
    name: Low temp today
  - entity: sensor.dark_sky_forecast_precip_intensity_0d
    name: Intensity today
- etc etc

  - type: custom:fold-entity-row
    head:
      type: section
      label: Tomorrow
    padding: 0
    entities:
      - entity: sensor.dark_sky_forecast_icon_1d
        name: Condition tomorrow
      - entity: sensor.dark_sky_forecast_daytime_high_temperature_1d
        name: High temp tomorrow
etc etc

  - type: custom:fold-entity-row
    head:
      type: section
      label: Day after tomorrow
    padding: 0
    entities:
      - entity: sensor.dark_sky_forecast_icon_2d
        name: Condition 2 day
      - entity: sensor.dark_sky_forecast_daytime_high_temperature_2d
        name: High temp 2 day
etc etc


# End of code
```

Error messages from the browser console:

none
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
