### ISSUE TITLE
Card-Head doesn't get rendered correctly while casting

### ISSUE THREAD

**Issue by Fabenissimo** [thomasloven/lovelace-fold-entity-row#102]
My Home Assistant version: 0.110.1

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Casting an entities card in a Lovelace view to my Google Nest Hub (or any other cast enabled deivce) following this example: https://github.com/thomasloven/lovelace-fold-entity-row#advanced

What I expected to happen:
The cards to show exactly as on my PC/Phone/Laptop/Tablet

What happened instead:
One of my fold-entity-row- elements shows empty.

**Minimal** steps to reproduce:
Cast the card via the code below to a cast enabled device

```yaml
# The least ammount of code possible to reproduce my error
  - entities:
      - entity: light.fabian_steckdose_stehlampe
        icon: 'mdi:power-socket-eu'
        name: Stehlampe
      - entity: light.fabian_steckdose_tv_schrank
        icon: 'mdi:power-socket-eu'
        name: TV-Schrank
      - entities:
          - entity: sensor.home_attic_fabian_socketaircon_power
            name: Aktuell
        entity: switch.home_attic_fabian_socketaircon_switch
        icon: 'mdi:power-socket-eu'
        name: Klimaanlage
        state_color: true
        toggle: true
        type: 'custom:multiple-entity-row'
    head: group.power_sockets_fabian
    open: false
    type: 'custom:fold-entity-row'
# End of code
```

Error messages from the browser console:
Not possible AFAIK on a cast device

Additional info from my side:
Before 109.x the card always showed an error, I can't recall it 100%, but it was something along the lines of ```custom element doesn't exist: "hui:group-entity-row"``` or ```custom element doesn't exist: "group-entity-row"```. Since 109.X it doesn't show an error, it just shows blank with the fold-icon on the right hand side. At some point I found out that if I would add an group entity to any entities-card in this view the group-entity in the fold-entity-row also would load, but if I remove it again it won't show correctly after the view gets reloaded on the cast.

The photos of what it looks on my Nest Hub are here:
https://imgur.com/a/RyWLxfL

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
