### ISSUE TITLE
state_color not working

### ISSUE THREAD

**Issue by SupremeSports** [thomasloven/lovelace-fold-entity-row#103]
A device (switch, sensor, etc.), that has some custom icon_color, works perfectly out of the fold card, but inside the fold card, no more colors
![Untitled](https://user-images.githubusercontent.com/13887820/82731866-a518f780-9cd7-11ea-83db-80b01f9023df.jpg)

The first Pool Pump is the normal switch with colors set up. The second one is a binary sensor with colors set up. then the third one is the same switch as the top one and has colors set up

```
    - type: entities
      title: Pool pump and heater
      show_header_toggle: false
      state_color: true
      entities:
        - switch.pool_pump
        - type: custom:fold-entity-row
          head: binary_sensor.poolpump_status
          entities:
          - switch.pool_pump
          - input_select.poolpump_mode
          - type: custom:fold-entity-row
            head:
              type: section
              label: Automations
            entities:
              - automation.pool_pump_control
```
