### ISSUE TITLE
resource path change

### ISSUE THREAD

**Issue by yuckypants** [thomasloven/lovelace-fold-entity-row#105]
My Home Assistant version: 0.110.0

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Viewing fold-entity-row card on lovelace

What I expected to happen: card would display with option to change themes

What happened instead: received error - custom element doesn't exist

**Minimal** steps to reproduce: view lovelace with card config enabled

```yaml
# The least ammount of code possible to reproduce my error

entities:
  - entities:
      - input_select.theme
      - input_boolean.theme_alternative
    head: input_boolean.dark_mode
    type: 'custom:fold-entity-row'
type: entities


https://myURL.duckdns.org/config/lovelace/resources
resources tab
/local/fold-entity-row.js
js module


# End of code
```

Error messages from the browser console: custom element doesn't exist

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X ] Have made sure I am using the latest version of the plugin.
- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**I fixed by updating the resource value from /local/fold-entity-row.js to /local/community/lovelace-fold-entity-row/fold-entity-row.js**
