### ISSUE TITLE
Add friendly name for entity in "head"

### ISSUE THREAD

**Issue by Rikkie80** [thomasloven/lovelace-fold-entity-row#106]
It would be nice if you can add a friendly name for the entity mentioned in the head:

```  
  - entities:
      - entity: light.xxx
      - entity: light.yyy
    head: light.living_kitchen
    name: Living and Kitchen lights #(or title:?)
    type: 'custom:fold-entity-row'
```

Tried also with label but that didn't work
