### ISSUE TITLE
User defined Label and other customizations not displaying

### ISSUE THREAD

**Issue by hathalud** [thomasloven/lovelace-fold-entity-row#107]
My Home Assistant version: 0.110.3

My lovelace configuration method (GUI or yaml): 
yaml in gui

What I am doing:
Trying to define how the header looks, showing the label of the card and not displaying the toggle.

What I expected to happen:
I expect to see the custom defined label for the entity to display and to not see the toggle show.

What happened instead:
The toggle shows and the default label of the entity displays.

**Minimal** steps to reproduce:
Plugin was recently reinstalled via HACS after being updated to latest version of both HACS and the plugin.

```yaml
# The least amount of code possible to reproduce my error

  - type: 'custom:fold-entity-row'
    head:
      type: section
      label: Livingroom
      toggle: false
    entity: light.livingroom
    icon: 'mdi:ceiling-light'

# End of code
```

Error messages from the browser console:

FOLD-ENTITY-ROW 1.0.2 IS INSTALLED 

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [ X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X ] Have made sure I am using the latest version of the plugin.
- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
