### ISSUE TITLE
cannot read property 'appendChild' of null

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#109]
My Home Assistant version: 0.111.2

My lovelace configuration method (GUI or yaml):

yaml
What I am doing:

What I expected to happen:

no error?

What happened instead:
besides the errors in the inspector, nothing really. Cards seem to show as expected.

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
type: entities
entities:
  - type: custom:hui-element
    card_type: markdown
    title: |
      Home Assistant --> Google Assistant
      Voice commands
    style: |
      ha-card {background: url('/local/various/google_assistant.png');
               background-size: cover;
               box-shadow: none;
               margin: -16px -16px 0px -16px;
               }
    content: |
      Ok/Hey Google,
      --> <i>'activity/mode'</i> <b>activeren</b>
      --> <b>turn-on/off</b> <i>'switch/verlichting'</i>
      --> <i>'switch/verlichting'</i> <b>in-/uitschakelen</b>
  - type: custom:fold-entity-row
    head:
      type: section
      label: Activities
    padding: 0
    entities:
      - !include /config/lovelace/includes/include_alias_activities.yaml

  - type: custom:fold-entity-row
    head:
      type: section
      label: Switches
    padding: 0
    entities:
      - !include /config/lovelace/includes/include_alias_switches.yaml

  - type: custom:fold-entity-row
    head:
      type: section
      label: Lighting
    padding: 0
    entities:
      - !include /config/lovelace/includes/include_alias_lighting.yaml


# End of code
```

for full disclosure and debugging, any of the includes above is in this form:

```
type: custom:hui-element
card_type: markdown
style: |
  ha-card {
    background: 'var(--paper-card-background-color)';
    box-shadow: none;
    }
content: |
    Aan de slag:
      ---> Werk

    Gaming:
      ---> Xbox

    Gym:
      ---> Sports

    Home theater:
      ---> Film kijken, Bioscoop, Movie
```

Error messages from the browser console:

Chrome:
<img width="730" alt="Schermafbeelding 2020-06-14 om 23 54 28" src="https://user-images.githubusercontent.com/33354141/84605040-7d621d00-ae9a-11ea-9df1-0b398819cfbc.png">

Safari Mac:
<img width="725" alt="Schermafbeelding 2020-06-14 om 23 55 35" src="https://user-images.githubusercontent.com/33354141/84605048-966ace00-ae9a-11ea-8565-fa80e9df5d22.png">

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by rccoleman** [comment]
I'm seeing an error that's vaguely similar and only appears if I try to style within `group_config:`.  The styling doesn't actually take effect, so it **does** have a meaningful impact.

![image](https://user-images.githubusercontent.com/860888/86282037-53e00b80-bb93-11ea-8ac2-e3cdf2e3a563.png)

The card definition that tickles it is quite simple, and used to work fine:

```
                - type: entities
                  entities:
                    - type: custom:fold-entity-row
                      head: group.downstairs_lights
                      group_config:
                        style: |
                          :host {
                            --paper-item-icon-color:
                              {% if states(config.entity) == 'on' %} red;
                              {% else %} green;
                              {% endif %}
                          }
```

If I remove the `style:` tag and replace it with something simple, such as modify the secondary_info, there's no error.

If this is a different issue, I can create a separate issue.

**Comment by thomasloven** [comment]
It's the same issue. Has to do with lazy-loading of cards. I'll have a solution up soon.

**Comment by rccoleman** [comment]
Excellent, thanks!  I didn’t want to confuse the issue earlier, but the same code does sometimes work in the iOS app (like right now), but never works in Chrome on my desktop. Looking forward to the update.

**Comment by thomasloven** [comment]
It's quite possible you have actually been running into two problems at once, @Mariusthvdb. Please confirm if [release 18](https://github.com/thomasloven/lovelace-fold-entity-row/releases/tag/18) is working for you.

**Comment by Mariusthvdb** [comment]
sure I will.
you have a few custom cards that dont show the version info in inspector but some other number:

<img width="335" alt="Schermafbeelding 2020-07-03 om 11 55 28" src="https://user-images.githubusercontent.com/33354141/86457536-1bbc0280-bd24-11ea-916a-930d96e8bbf1.png">

making it less than obvious to check if the correct version is loaded. Would you be willing to change that please to show 'Version 18'

like these:
<img width="371" alt="Schermafbeelding 2020-07-03 om 11 56 39" src="https://user-images.githubusercontent.com/33354141/86457655-49a14700-bd24-11ea-8f28-6b7354f18c1d.png">

bak to testing, and, thanks for updating!

**Comment by rccoleman** [comment]
I’m not seeing the errors anymore with 18, but it hasn’t really helped with functionality that I described above. Styling within the group seems to work about 10% of the time, and often simply refreshing the page reverts back to the above behavior where group entity styling is ignored and the top-level styling affects all items.

How and why it works some of the time is quite vexing and I can’t reliably reproduce it. Creating a new view with just a fold-entity-row caused entity styling to work, but the behavior above returned as soon as I added a vertical-stack and remained broken even after I removed the vertical-stack. I often get different results on my iPhone, MacOS Chrome, and MacOS Safari with no rhyme or reason.  Clearing the cache and reloading doesn’t help, and often ‘breaks’ it if it was previously working.

I am getting a similar ‘addChild’ error in the console with the latest version of CardTools, and I don’t now whether that would interfere with this behavior, but I get no errors from fold-entity-row.

**Comment by thomasloven** [comment]
The error you're describing is inconsistent with the two code examples you show above. There are four ways to apply styles in a fold entity row:
```
type: custom:fold-entity-row
style: |
  A: This is applied to the row in the entities card, and will apply to EVERYTHING in the fold entity row
head:
  entity: ...
  style: |
    B: This is applied to the head element
group_config:
  style: |
    C: This is applied to every element in the fold
entities:
  - entity: ...
    style: |
      D: This is applied only to this entity in the fold
```

Are you using A and C at the same time? Please update your code examples to show what you are actually doing that's not working.

If you get an error from card-tools its probably a problem with whatever plugin you are using that requires card-tools to be installed. None of my plugins do, and card-tools has nothing to do with styling anyway.

**Comment by thomasloven** [comment]
@Mariusthvdb I Cannot reproduce the problem.
```yaml
type: entities
entities:
  - type: 'custom:fold-entity-row'
    head: light.bed_light
    entities:
      - type: 'custom:hui-markdown-card'
        content: Test
        style: |
          ha-card {
            color: blue;
          }
```
 Please provide a minimal example that reproduces the problem.

**Comment by Mariusthvdb** [comment]
ok so if I include this:

```
type: custom:hui-element
card_type: markdown
#style: |
#  ha-card {
#    background: 'var(--paper-card-background-color)';
#    box-shadow: none;
#    }
content: |
    Aan de slag:
      ---> Werk

    Gaming:
      ---> Xbox

    Gym:
      ---> Sports

    Home theater:
      ---> Film kijken, Bioscoop, Movie
```

the error is gone, using

```
type: custom:hui-element
card_type: markdown
style: |
  ha-card {
    background: 'var(--paper-card-background-color)';
    box-shadow: none;
    }
content: |
    Aan de slag:
      ---> Werk

    Gaming:
      ---> Xbox

    Gym:
      ---> Sports

    Home theater:
      ---> Film kijken, Bioscoop, Movie
```
makes it appear.

**Comment by thomasloven** [comment]
Great! I can reproduce it, but only when using hui-element.

**Comment by thomasloven** [comment]
Try now. https://github.com/thomasloven/lovelace-fold-entity-row/releases/tag/19

**Comment by Mariusthvdb** [comment]
Bingo!
you made it disappear!
thank you so much

**Comment by Mariusthvdb** [comment]
however....
could it be this now causes this to happen:

using:
```
      - type: custom:fold-entity-row
        head:
          type: section
          label: Alerts settings/selectors
        padding: 0
        entities:
          - input_number.quakes_near
          - input_select.quakes_near
```

<img width="373" alt="Schermafbeelding 2020-07-04 om 15 40 09" src="https://user-images.githubusercontent.com/33354141/86513759-1981a300-be0d-11ea-892e-2a223552852e.png">

clicking the arrow:

<img width="365" alt="Schermafbeelding 2020-07-04 om 15 41 59" src="https://user-images.githubusercontent.com/33354141/86513762-21414780-be0d-11ea-96b7-c849bca256bc.png">

**Comment by rccoleman** [comment]
> The error you're describing is inconsistent with the two code examples you show above. There are four ways to apply styles in a fold entity row:
> 
> ```
> type: custom:fold-entity-row
> style: |
>   A: This is applied to the row in the entities card, and will apply to EVERYTHING in the fold entity row
> head:
>   entity: ...
>   style: |
>     B: This is applied to the head element
> group_config:
>   style: |
>     C: This is applied to every element in the fold
> entities:
>   - entity: ...
>     style: |
>       D: This is applied only to this entity in the fold
> ```
> 
> Are you using A and C at the same time? Please update your code examples to show what you are actually doing that's not working.

Sorry, I can see how my terminology was confusing.  My goal is to start with a fold that automatically expands a group, and without styling I'm using this:

```
        - type: custom:fold-entity-row
          head: group.upstairs_lights
```

Which turns into this:

<img width="960" alt="Screen Shot 2020-07-04 at 7 43 32 AM" src="https://user-images.githubusercontent.com/860888/86514993-de5e8000-bdca-11ea-9dfc-6ab97f84b1fd.png">

I would like the icons for the group members to change color according to their state (on == red, off == green), and for the "head" (group name) to change color based on the states of the members (**any** are on == red, **all** are off == green).  In this case, the icons for the head ("Upstairs Lights") and "Guest Bathroom" should be red and the rest of the icons should be green.  The code that I've been using is this:

```
        - type: custom:fold-entity-row
          head: group.upstairs_lights
          style: |
            :host {
              --paper-item-icon-color:
                {% if is_state('group.upstairs_lights', 'on') %} red
                {% else %} green
                {% endif %}
                  ;
            }
          group_config:
            style: |
              :host {
                --paper-item-icon-color:
                  {% if is_state(config.entity, 'on') %} red
                  {% else %} green
                  {% endif %}
                    ;
                }
```

This has worked before, and works now about 10% of the time with the variability that I mentioned in my last post between browser and device.  Most of the time, I end up with something like this, where even the members of the fold which are 'off' are colored red when at least one is 'on':

<img width="957" alt="Screen Shot 2020-07-04 at 8 03 44 AM" src="https://user-images.githubusercontent.com/860888/86515356-24b4de80-bdcd-11ea-9461-7346d91240db.png">

I've also tried a simpler approach where I just do this:

```
        - type: custom:fold-entity-row
          head: group.upstairs_lights
          style: |
            :host {
              --paper-item-icon-color: green;
              --paper-item-icon-active-color: red;
            }
          group_config:
            style: |
              :host {
                --paper-item-icon-color: green;
                --paper-item-icon-color: red;
                }
```

This approach resolved [this issue](https://github.com/thomasloven/lovelace-card-mod/issues/29), but all the icons just stay green in fold-entity-row regardless of the states of the head or members.

I don't think this matches any of the four options you laid out, so perhaps that's the problem.  My code is using A & C, but the closest to my intent would be B & C, but combined with the "_Setting head: to a group will populate the entities list with the entities of that group._" feature described in the docs.

I've also tried something like this, but VSCode hates it ("bad indentation of a mapping entry") I get the following error.

```
        - type: custom:fold-entity-row
          head: group.upstairs_lights
            style: |
              :host {
                --paper-item-icon-color: green;
                --paper-item-icon-active-color: red;
              }

          group_config:
            style: |
              :host {
                --paper-item-icon-color: green;
                --paper-item-icon-active-color: red;
                }
```

`mapping values are not allowed here in "/config/ui-lovelace.yaml", line 879, column 18`

If I'm doing something wrong or it's just not supported, please let me know.  Otherwise, I'm happy to open another issue now that my symptoms don't really match this one.

**Comment by thomasloven** [comment]
If you use the last one (B and C) but change to
```yaml
head:
  entity: group.upstairs_lights
  style: |
    ...
```
it should work.
