### ISSUE TITLE
Entity Head With Custom Name

### ISSUE THREAD

**Issue by miguelcaravantes** [thomasloven/lovelace-fold-entity-row#113]
Currently i don't see any option to override the Friendly Name in the head, I can do with the children entities but not in head, is there a option, or anyone can add this feature?

nevermind I found the solution in the code, it's only i didn't find the readme.

use entity property instead of head solves the issue

**Comment by marecabo** [comment]
Example

```yaml
- type: custom:fold-entity-row
  entity:
    entity: switch.adaptive_lighting_dormer
    name: Dormer
  items:
    - # your other entities as usual
```
