### ISSUE TITLE
[FR] Click on head entity to collapse/expand 

### ISSUE THREAD

**Issue by david-kalbermatten** [thomasloven/lovelace-fold-entity-row#116]
I'd like to be able to remove the fold-indicator and instead use the entity itself to expand/collapse the `fold-entity-row` by clicking on the part between the icon and toggle/state (the highlighted part of the image)
```yaml
  - type: 'custom:fold-entity-row'
    hide_indicator: true
    head: light.generic_example_lamp
    entities:
     - switch.generic_example_switch
     - ...
```
![image](https://user-images.githubusercontent.com/45201085/87956811-c287f900-caaf-11ea-9c8b-95a8910c35b8.png)
