### ISSUE TITLE
Type: section not working

### ISSUE THREAD

**Issue by jer78** [thomasloven/lovelace-fold-entity-row#12]
Not sure what I'm doing wrong but can't get type: section to work:

Here's what's happening:

![img_1852](https://user-images.githubusercontent.com/1253286/48011216-340df100-e0ed-11e8-9982-6cc39a4ff080.gif)

And my config:

```
        - type: entities
          entities:
            - type: custom:fold-entity-row
              head: sensor.ideal_ecobee_mode
              items:
                - entity: sensor.ideal_ecobee_mode
                  name: Ideal Mode
                  icon: mdi:thermostat
                - entity: input_boolean.change_mode_on_outside_temp
                  icon: mdi:calendar
                - entity: sensor.average_apparent_temperature
                  name: Average Apparent Temperature
                  icon: mdi:thermometer
                - entity: input_number.ecobee_mode_day_count
                - entity: input_number.ecobee_mode_cool_point
                - entity: input_number.ecobee_mode_heat_point
            - type: custom:fold-entity-row
              head:
                type: section
                label: Climate
              items:
                - entity: sensor.ideal_ecobee_mode
                  name: Ideal Mode
                  icon: mdi:thermostat
                - entity: input_boolean.change_mode_on_outside_temp
                  icon: mdi:calendar
                - entity: sensor.average_apparent_temperature
                  name: Average Apparent Temperature
                  icon: mdi:thermometer
                - entity: input_number.ecobee_mode_day_count
                - entity: input_number.ecobee_mode_cool_point
                - entity: input_number.ecobee_mode_heat_point
```
