### ISSUE TITLE
Unwanted canvas offset on the right (mobile)

### ISSUE THREAD

**Issue by acseven** [thomasloven/lovelace-fold-entity-row#124]
My Home Assistant version:0.113.3

**What I am doing:**
Just adding entitites to a fold-entity-row

**What I expected to happen:**
No weird offset on the right

**What happened instead:**
Appears weird offset on the right, see screenshot below. It's the same issue with the default theme. 

![s](https://user-images.githubusercontent.com/1176371/98449046-51388880-2128-11eb-834c-26d3246bda93.png)

On a desktop browser it's visually okay but that padding is still there, check video (this is using Chrome's dev tools):

![vid-Trim](https://user-images.githubusercontent.com/1176371/98449192-6f52b880-2129-11eb-97e7-c1e64562a92b.gif)

Also, I set "padding: 0" as well, but didn't help with this. though it does change the left padding. 

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by mkanet** [comment]
I am having the same issue.  I've tried all sorts of things but, this card seems to just ignore the card's right padding:

![1](https://user-images.githubusercontent.com/811008/99180799-4a88b300-26de-11eb-8880-97d8bde67c12.png)
![2](https://user-images.githubusercontent.com/811008/99180800-4ceb0d00-26de-11eb-9ec3-f004d565ea23.png)

@thomasloven, is this a new bug?

**Comment by Ernie11** [comment]
Hello,
I have this issue on both mobile and desktop. It seems the default left padding is 20px so using css I added a right padding of 20px and this fixed it but since im not to good with card mod I was unable to make a style out of it to add to my code. Maybe a solution can be to have a left and right padding option instead of only a left padding.

**Comment by thomasloven** [comment]
Is this still an issue?

**Comment by acseven** [comment]
Yes, just updated to 20.0.0 and no change!

**Comment by acseven** [comment]
Hi,
Just updated to the latest version (20.0.3) and I can confirm that the extra offset is no longer present (content stays inside the viewport at all times), but there's still a weird placement issue when compared to a regular entity row.

In the screenshot below, the first 3 are simple entities, followed by a fold-entity-row.

![IMG_C6FC8F450993-1](https://user-images.githubusercontent.com/1176371/111234209-f4714100-85e5-11eb-933b-afe539cfb659.jpeg)

**Comment by thomasloven** [comment]
Could you please share the code for that entire card?

**Comment by acseven** [comment]
> Could you please share the code for that entire card?

I've just sent you an email with the code.

**Comment by thomasloven** [comment]
... the YAML code for the entire card...

**Comment by acseven** [comment]
Here's the code:

```
entities:
  - cover.all_shutters
  - entity: cover.all_shutters
    full_row: true
    type: 'custom:slider-entity-row'
  - cover.north_window_shutters
  - entity: cover.north_window_shutters
    full_row: true
    type: 'custom:slider-entity-row'
  - cover.east_window_shutters
  - entity: cover.east_window_shutters
    full_row: true
    type: 'custom:slider-entity-row'
group_config:
  icon: mdi-window-shutter
head:
  label: Estores Agrupados
  type: section
padding: 5
title: Estores Agrupados
type: 'custom:fold-entity-row' 
```
