### ISSUE TITLE
yellow backround and hui-error-card in Home Assistant 0.118.0 and Firefox 68.1.0

### ISSUE THREAD

**Issue by lukastillmann** [thomasloven/lovelace-fold-entity-row#125]
My Home Assistant version: 0.118.0

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:

I use fold-entity-row to hide some of the settings for less regularly used switches/lights/automation

What I expected to happen:

![grafik](https://user-images.githubusercontent.com/17717159/99782493-85914900-2b19-11eb-860c-a9764097700f.png)
(in Chrome 87.0.4280.66)

What happened instead:

![grafik](https://user-images.githubusercontent.com/17717159/99782518-8de98400-2b19-11eb-8f5a-d7140a86962c.png)
(in Firefox 68.1.0esr (64-Bit)

![grafik](https://user-images.githubusercontent.com/17717159/99783253-7959bb80-2b1a-11eb-80c1-2323c34afaf1.png)

**Minimal** steps to reproduce:

Windows 10, Firefox 68.1.0esr (64-Bit)

```yaml
# The least ammount of code possible to reproduce my error

type: entities
entities:
  - type: 'custom:fold-entity-row'
    head:
      type: section
      label: Sonstiges
    style: |
      card-mod {
        display: none;
      }    
    open: false
    padding: 0
    entities:
      - switch.stern

# End of code
```

Error messages from the browser console:

![grafik](https://user-images.githubusercontent.com/17717159/99782956-18ca7e80-2b1a-11eb-8cff-a8535efbde93.png)

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [ x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [ x] Have made sure I am using the latest version of the plugin.
- [ x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [ x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
