### ISSUE TITLE
Head set name unclear 

### ISSUE THREAD

**Issue by realjax** [thomasloven/lovelace-fold-entity-row#126]
First of all, I saw the readme, and I saw  https://github.com/thomasloven/lovelace-fold-entity-row/issues/106

I tried everything ( I think ) but cant for the life of me change the name of the head!

```
  - entities:
      - entity: light.xxx
      - entity: light.yyy
    head: light.living_kitchen
    type: 'custom:fold-entity-row'
```

What *is* the correct syntax to change the name of the head from, in the above example 'Living kitchen' to something else? All I could find ( and which also worked fine) is how to chnage the name of the entities, so for instance

```
  - entities:
      - entity: light.xxx
         name: The Great X light
      - entity: light.yyy
    head: light.living_kitchen
    type: 'custom:fold-entity-row'
```

The above works fine, but that is the name of an entity and I want to change the name of the head.

**Comment by realjax** [comment]
never mind, found out the correct syntax, it should be 

```
  - entities:
      - entity: light.xxx
      - entity: light.yyy
    head: 
      entity: light.living_kitchen
      name: BunchOLights
    type: 'custom:fold-entity-row'
```

I was pretty sure I tried that one already but probably didn't.
Thanks for being my rubber ducky 👍
