### ISSUE TITLE
add a custom card in fold-entity-row card

### ISSUE THREAD

**Issue by hekm77** [thomasloven/lovelace-fold-entity-row#13]
It is possible to add a custom card in fold-entity-row card?
I would like to set the icons color using card-modder card.
Now they are cropped.
<img width="476" alt="333" src="https://user-images.githubusercontent.com/22895433/48303560-dbcf5880-e50b-11e8-8e32-924a53dca277.png">
```
          - id: test_printer
            type: entities
            title: Epson Ink Level
            entities:
              - type: custom:fold-entity-row
                head:
                  entity: sensor.epson
                  icon: mdi:printer
                items:
                  - type: custom:card-modder
                    style:
                      --paper-item-icon-color: cyan
                    card:
                      type: entities
                      entities:
                        - sensor.epson_ink_level_cyan
                  - type: custom:card-modder
                    style:
                      --paper-item-icon-color: yellow
                    card:
                      type: entities
                      entities:
                        - sensor.epson_ink_level_magenta
                  - type: custom:card-modder
                    style:
                      --paper-item-icon-color: magenta
                    card:
                      type: entities
                      entities:
                        - sensor.epson_ink_level_magenta 
```

**Comment by thomasloven** [comment]
I'm not sure this will work, but you could try
```yaml
items:
  - type: custom:card-modder
    style:
      --paper-item-icon-color: cyan
    card:
      type: custom:hui-text-entity-row
      entity: sensor.epson_ink_level_cyan
```
