### ISSUE TITLE
Group Head - device_class Ignored

### ISSUE THREAD

**Issue by Nelinski** [thomasloven/lovelace-fold-entity-row#131]
Hi, 

Not sure if this is a bug or expected behaviour.

My Home Assistant version: 2020.12.1

My lovelace configuration method (GUI or yaml):
```
  - type: 'custom:fold-entity-row'
    head:
      entity: group.motion_sensors
      state_color: true
    group_config:
      state_color: true
    entities:
      - binary_sensor.downstairs_hallway_motion
      - binary_sensor.upstairs_hallway_motion
      - binary_sensor.kitchen_dining_room_motion
```

What I am doing:
N/A

What I expected to happen:
The group head to reflect the correct on/off device class set. E.g. instead of the group head saying 'on', it should say 'detected'. Or for Windows/Doors it should say 'open'.

What happened instead:
UI in Home Assistant:
![image](https://user-images.githubusercontent.com/6281940/102717971-6be04e80-42dd-11eb-9423-9e2cf669c0b8.png)

Home Assistant Configuration.yaml snippet:
![image](https://user-images.githubusercontent.com/6281940/102717981-7c90c480-42dd-11eb-8898-30bab29de2b9.png)

**Minimal** steps to reproduce:
Try use a "group" as a head entity. Override the device_class for the group in the Settings->Customizations section.

```yaml
# The least amount of code possible to reproduce my error
See lovelace config above.


# End of code
```

Error messages from the browser console:
N/A

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
