### ISSUE TITLE
Padding not working when stacking cards together

### ISSUE THREAD

**Issue by mkanet** [thomasloven/lovelace-fold-entity-row#132]
**My Home Assistant version: 2021.1.4**

**My Lovelace configuration method (GUI or YAML):** GUI

**What I am doing:**
Stacking cards vertically... padding not lining up.

**What I expected to happen:**
When stacking cards vertically, fold-entity-row's padding (left and right borders) should match the standard padding that all other Lovelace cards use.

**What happened instead:**
fold-entity-row card's padding does match any of my Lovelace cards.  I have tried padding: 0` as well as other values.
![fold-entity-row-paddingissue](https://user-images.githubusercontent.com/811008/105409903-fc17f900-5be5-11eb-9246-e833877caf9b.png)

****Minimal** steps to reproduce:**
Use code shown below to reproduce

```yaml
# The least ammount of code possible to reproduce my error
cards:
  - card: null
    entities:
      - entity: sensor.blank_sensor
        image: /local/images/Al.png
        name: Al
        style: |
          :host {
            color: #A5AEB7;
            font-size: 16px;
            font-weight: bold;
          }
      - entity: sensor.sm_a505u_battery_level
        name: Battery Level
      - entity: sensor.sm_a505u_battery_state
        name: Battery State
      - entity: sensor.sm_a505u_wifi_connection
        name: Wi-fi
      - entity: sensor.alina_location
    show_header_toggle: false
    type: entities
  - card: null
    type: 'custom:fold-entity-row'
    head:
      type: section
      label: More..
    padding: 0
    group_config: null
    entities:
      - entity: device_tracker.sm_a505u
      - entity: sensor.sm_a505u_audio_mode
mode: vertical
type: 'custom:stack-in-card'


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
