### ISSUE TITLE
Icon: 'true/false' and state_colour: 'true/false' not working when groups used in fold header.

### ISSUE THREAD

**Issue by Andrewpaps** [thomasloven/lovelace-fold-entity-row#133]

**Comment by bcutter** [comment]
It even does not work when not using groups but a single entity in header.

The cornering entity card has `state_color: true' but it is not applied neither to the fold head nor to its childs. Example:

```
  - entity: sensor.fritz_box_call_monitor
  - type: 'custom:fold-entity-row'
    head: switch.fritzbox_7590_ui_guest_wifi
    padding: 0
    open: false
    entities:
      - entity: switch.fritzbox_7590_ui_wifi
      - entity: switch.fritzbox_7590_ui_wifi_5ghz
title: ''
state_color: true
```

Result:

![grafik](https://user-images.githubusercontent.com/13799156/105579736-9f087880-5d88-11eb-95a4-09fde658a7bd.png)

**Comment by direx1** [comment]
Like this..

`type: custom:fold-entity-row
head:
  type: section
  label: group_config
group_config:
  state_color: true`

**Comment by direx1** [comment]
```
type: custom:fold-entity-row
head:
  type: section
  label: group_config
group_config:
  state_color: true
```

**Comment by bcutter** [comment]
> Like this by adding group_config
> 
> ```
> 
> type: custom:fold-entity-row
> 
> head:
> 
>   type: section
> 
> group_config:
> 
>   state_color: true
> 
> ```

?

**Comment by bcutter** [comment]
> Like this by adding group_config
> 
> ```
> 
> type: custom:fold-entity-row
> 
> head:
> 
>   type: section
> 
> group_config:
> 
>   state_color: true
> 
> ```

Tested, works. BUT: I don't want to waste the head by using a section but prefer showing an entity. This should just be fixed.

**Comment by direx1** [comment]
It works just using

```
group_config:
  state_color: true
```

**Comment by bcutter** [comment]
Alright, now the child's are colored. But what about the main row?

![image](https://user-images.githubusercontent.com/13799156/108633649-9ed9c680-7475-11eb-93f5-d4b80c2d5233.jpeg)

It ignores the "state_color: true".

**Comment by direx1** [comment]
> Alright, now the child's are colored. But what about the main row?
> 
> ![image](https://user-images.githubusercontent.com/13799156/108633649-9ed9c680-7475-11eb-93f5-d4b80c2d5233.jpeg)
> 
> It ignores the "state_color: true".

Add `state_color:  true` to the same indent level as the `head:` probably near the bottom of the entire script would be ideal. Have a play about with it.

**Comment by bcutter** [comment]
I did. Nothing worked. Normal entities card, all others work except custom:fold-entity-row.

**Comment by direx1** [comment]
![Screenshot_20210221-180349_Chrome](https://user-images.githubusercontent.com/77240604/108633980-325bc900-746f-11eb-8a75-edb025dd04cc.jpg)

Sorry but same level as the `entities:` like this.

**Comment by bcutter** [comment]
I have it exactly like that. Icon stays blue.

It seems to be a bug. When I open the head entity on more info popup it is shown yellow.

**Comment by Andrewpaps** [comment]
As noted in the description, this issue pertains to a bug with the fold/first header. Both state toggle and icon toggle. Children work fine.

**Comment by thomasloven** [comment]
Please try version 20.0.0

**Comment by Andrewpaps** [comment]
No luck. Still an issue.

**Comment by Andrewpaps** [comment]
Just an update that as of version 20.0.3 this continues to be a bug. Actually, all 'group_config' options for group headers that auto-populate the drop-down lists don't work.

**Comment by bcutter** [comment]
> 
> 
> Just an update that as of version 20.0.3 this continues to be a bug. Actually, all 'group_config' options for group headers that auto-populate the drop-down lists don't work.

Yes, I can confirm. https://github.com/thomasloven/lovelace-fold-entity-row/releases/tag/20.0.1 looked promising, but it fixes another issue (#139) while this one is #133... :-(

With 20.0.3 still:
![grafik](https://user-images.githubusercontent.com/13799156/110209502-44853080-7e8d-11eb-8293-8e67cc52c999.png)

**Comment by Aura-Mancer** [comment]
I had the same issue. You have to add "state_color: true" to the head. Like this:

```
- type: 'custom:fold-entity-row'
    head:
      entity: light.example
      name: Example
      state_color: true
```
