### ISSUE TITLE
iOS, 125% zoom in app & cover entity

### ISSUE THREAD

**Issue by RobHofmann** [thomasloven/lovelace-fold-entity-row#134]
First of all: thanks for your plugin man. I've been using this for a good while now. This is by far my most used plugin in my installation! I love it!

My Home Assistant version: 2021.2.1 (Docker). In the previous version I did not encounter this bug.

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Opening the app on my iPhone 12 Pro Max

What I expected to happen: Fold entity row buttons don't overlap with the cover entity controls

What happened instead: They did overlap

**Minimal** steps to reproduce: 
1. Use YAML below to create the fold entity row with a cover entity as header row. 
2. Open Home Assistant app on your iOS device
3. Set zoom to 125% (only tested with 125%)
4. Go view your fold entity row
5. Can't click the button because controls are overlapping with the foldbutton

```yaml
      - entities:
          - label: Rolluiken
            type: section
          - cover.zolderkamer_rolluik_links
          - cover.zolderkamer_rolluik_rechts
          - label: Gordijnen
            type: section
          - cover.zolderkamer_gordijnen_voor
          - cover.zolderkamer_gordijnen_achter
        head:
          entity: cover.zolderkamer_blindering
        type: 'custom:fold-entity-row'
```

Error messages from the browser console:
N.a.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
