### ISSUE TITLE
Fold-entity-row only shows the pull down arrow

### ISSUE THREAD

**Issue by pdwonline** [thomasloven/lovelace-fold-entity-row#137]
My Home Assistant version: 2021.2.3

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
I used fold-entity-row a lot in my previous version. Since I switched to ZWaveJS, I had to reconfigure alle elements.
I configured it as I did before. (note: before I configured everything from Yaml). This is one of my entity card configs:

```
type: entities
entities:
  - type: 'custom:fold-entity-row'
    head: switch.double_switch_2_current_value_5
    entities:
      - switch.double_switch_2_current_value_5
      - automation.badkamerventilator_aan
      - binary_sensor.bathroom_hygrostat
  - switch.double_switch_2_current_value_5
  - sensor.none_humidity
  - sensor.none_air_temperature
  - switch.wall_plug_switch_current_value_7
  - binary_sensor.bathroom_hygrostat
  - automation.badkamerventilator_aan
title: Badkamer
state_color: true

```

What I expected to happen:
I expected a pull down arror right beside the switch.double_switch_2_current_value_5 switch that reveals three defined entries when clicked. I also tried just a head, but that hads no result.

What happened instead:
Only the pull down arrow is visible. The editor gives a warning that is is not able to handle this in GUI with this message:

```
Visual editor is not supported for this configuration:

    The provided value for "entities.0" is not supported by the visual editor. We support (Object<{entity,name,icon,image,secondary_info,format,state_color,tap_action,hold_action,double_tap_action}> | string | Object<{type,name,action_name,tap_action,hold_action,double_tap_action}> | Object<{type,view,dashboard,name,icon,hide_if_unavailable}> | Object<{type,row,conditions}> | Object<{type,style}> | Object<{type,label}> | Object<{type,url,name,icon}> | Object<{type,entities}> | Object<{type,entity,attribute,prefix,suffix,name}> | Object<{type,name,service,icon,action_name,service_data}>) but received ({"type":"custom:fold-entity-row","head":"switch.double_switch_2_current_value_5","entities":["switch.double_switch_2_current_value_5","automation.badkamerventilator_aan","binary_sensor.bathroom_hygrostat"]}).

You can still edit your config in YAML
```

**Minimal** steps to reproduce:
Paste the code above in the most recent version of HA

```yaml
# The least ammount of code possible to reproduce my error

type: entities
entities:
  - type: 'custom:fold-entity-row'
    head: switch.double_switch_2_current_value_5
    entities:
      - switch.double_switch_2_current_value_5
      - automation.badkamerventilator_aan
      - binary_sensor.bathroom_hygrostat

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
