### ISSUE TITLE
How bind template-entity-row into fold-entity-row?

### ISSUE THREAD

**Issue by charoon88** [thomasloven/lovelace-fold-entity-row#138]
Hey!

thanks a lot for these great plugins. This thread was very helpful for my problem. I installed the template-entity-row plugin and it works, but how do I bind the template-entity-row into the header of the fold-entity-row plugin?

I tried this: 
```yaml
- entities:
           - type: custom:template-entity-row
             name: 'Wetterdaten'
             secondary: "von {{states('sensor.time')}} Uhr"
           - type: custom:fold-entity-row
             head: Wetterdaten
             entities:
             - entity: sensor.wupws_uv
             - entity: sensor.wupws_preciprate 
             - entity: sensor.wupws_preciptotal
             - entity: sensor.wupws_windspeed
```
but it doesn't work.

charoon

__Originally posted by @charoon88 in https://github.com/thomasloven/lovelace-fold-entity-row/issues/81#issuecomment-787115711__
