### ISSUE TITLE
section line too short at right side of card

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#139]
My Home Assistant version: 0.XX.X
2021.3.2

My lovelace configuration method (GUI or yaml):
yaml
What I am doing:

<img width="505" alt="Schermafbeelding 2021-03-04 om 15 48 43" src="https://user-images.githubusercontent.com/33354141/109981897-a6189400-7d01-11eb-83df-030fe28f6cf8.png">

see yaml snippet
What I expected to happen:

to have the section line cover the full width of the card
What happened instead:

the section line is just that bit too short

also, we now need to click the exact fold down arrow, where if memory serves correctly we could click the whole line between label and arrow to make the row fold or close

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
  - type: custom:fold-entity-row
    head:
      type: section
      label: Sun & light
    padding: 0
    entities:
      - entity: binary_sensor.sun_up
        secondary_info: last-changed
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
