### ISSUE TITLE
Toggle lights do not change reported state in frontend

### ISSUE THREAD

**Issue by Aephir** [thomasloven/lovelace-fold-entity-row#14]
Hi,

Lately, the state doesn't change in the frontend (they still show as on, after I turn off). The "toggle button" flips to off, but back again to on, even as the light turns off.

As soon as I reload, or just switch to a different view, then they show the correct state.

I have the latest version of the `fold-entity-row.js` (updated today to be sure). This has been observed at least on HASS v 0.81.6 and 0.82.0 (my current version). I did not have this issue previously (at least not in 0.80.X versions)

In my `lovelace.yaml`, the layouts are generally similar to this:
```
          - type: custom:fold-entity-row
            head: light.kitchen_lights
            items:
            - entity: light.kitchen_spots
              type: custom:slider-entity-row
            - entity: light.kitchen_cabinet_lights
              type: custom:slider-entity-row
```

**Comment by thomasloven** [comment]
I can't reproduce this in either 0.81.6 or 0.82.0...
Did you try adding `?anything` after the url when importing `fold-entity-row.js`?

**Comment by Aephir** [comment]
> Did you try adding `?anything` after the url

I originally imported with:
```
wget https://raw.githubusercontent.com/thomasloven/lovelace-fold-entity-row/master/fold-entity-row.js
```

I just tried 
```
wget https://raw.githubusercontent.com/thomasloven/lovelace-fold-entity-row/master/fold-entity-row.js?anything
```

Same as before.


I did just notice a bunch of errors with custom cards, though, for fold-entity-row:
```
http://192.168.0.100:8123/local/fold-entity-row.js:75:0 SyntaxError: Unexpected use of reserved word 'let' in strict mode
```
But I think this didn't happen after I tried setting up an old iPad (I didn't see this before today).

**Comment by Aephir** [comment]
I'm not sure if this is helpful; I certainly don't understand why. But today I wanted to test a bit more, and added this:

```
          - type: custom:fold-entity-row
            head:
              type: section
              label: Lights
            group_config:
              secondary_info: last-changed
            items:
              - light.dining_table_lights
              - light.living_room_lightstrip
              - light.kitchen_lights
```

(together with the other `custom:fold-entity-row` "groups") to test one of the exact examples you gave. This works. And more surprisingly, after having added this, the other "groups" also update normally. Even after removing that test group from the config.

Absolutely no clue why, but I can no longer reproduce the initial error.

**Comment by houtknots** [comment]
I'm having the same problem as @Aephir [https://jhcs.xyz/xcDDS](url)
Below I have put my configuration if you want any more info please let me know.


Import plugin in lovelace:
```yaml
resources:
  - url: /local/lovelace/fold-entity-row.js
    type: js
```

The card config:
```yaml     
      - id: 9d5d9ea367sb6dfg48a580d2asdfa345fgh3521241234
        title: Kamers
        type: entities
        entities:
          - type: custom:fold-entity-row
            head: group.room1
            items:
              - switch.spots
              - switch.circle
              - switch.ledstripsbureau
              - switch.ledstripbed
              - switch.bedlamp
              - switch.onairlamp
              - switch.jayce_wereldbol
              - type: custom:fold-entity-row
                head: cover.front
                items:
                  - input_datetime.rolluikweekdayopen
                  - input_datetime.rolluikweekdaydicht
                  - input_datetime.rolluikweekendopen
                  - input_datetime.rolluikweekenddicht
          - type: custom:fold-entity-row
            head: group.zolder
            items:
              - type: custom:fold-entity-row
                head: cover.zolder
                items:
                  - input_datetime.rolluikzlopen
                  - input_datetime.rolluikzldicht
                  - input_datetime.rolluikzlopenmiddag
                  - input_datetime.rolluikzlsluitvoorzon
                  - input_boolean.zolderzlsluitvoorzon```
