### ISSUE TITLE
Clickable option set to true makes row fold but also opens secondary info

### ISSUE THREAD

**Issue by FredericMa** [thomasloven/lovelace-fold-entity-row#140]
My Home Assistant version: 2021.3.0

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
Created a fold-entity-row with head entity defined and clickable set to true.

What I expected to happen:
Only fold and unfold when I click the row.

What happened instead:
If I click the text or icon, the row folds and unfolds but also opens the secondary info window. If I click right underneath the text, the row folds and unfolds as expected. See gif below:
![ClickableIssue](https://user-images.githubusercontent.com/7840263/110086688-f986f280-7d92-11eb-930c-e27356e07b5b.gif)

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
  - type: entities
    title: Gelijkvloers
    entities:
      - type: custom:fold-entity-row
        head: group.lights_living_room_kitchen
        clickable: true
        padding: 5
        entities:
          - type: custom:slider-entity-row
            entity: light.living_room_sofa
            step: 1
# End of code
```

Error messages from the browser console:
None
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
