### ISSUE TITLE
Fold Entity row 2.0.3 dont work. 

### ISSUE THREAD

**Issue by hwikene** [thomasloven/lovelace-fold-entity-row#142]
My Home Assistant version: 2021.3.2

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Trying to make entity row for my frontend.

What I expected to happen: Fold entity row turn up with entities. 

What happened instead: I get "Custom element doesn't exist: fold-entity-row."

**Minimal** steps to reproduce: When i updated to Core 2021.3.2 it stopped working. Everything was ok in Core 2021.3.0
I have also updated card-mod to the latest version. 

```yaml
type: entities
entities:
  - light.wc
  - type: custom:fold-entity-row
    head: light.bed_light
    entities:
      - light.gang
      - light.vaskerom
```

Custom element doesn't exist: fold-entity-row.
type: 'custom:fold-entity-row'
head: light.bed_light
entities:
  - light.gang
  - light.vaskerom

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
