### ISSUE TITLE
Incorrect behavior in the Android mobile application

### ISSUE THREAD

**Issue by hqsone** [thomasloven/lovelace-fold-entity-row#143]
My Home Assistant version: 2021.3.2

My lovelace configuration method (GUI or yaml): yaml

Video: https://youtu.be/QNZAzrx63yA

**Minimal** steps to reproduce:

to redpoduce enough to have one card on view

``

```yaml
# The least ammount of code possible to reproduce my error
type: 'custom:fold-entity-row'
head:
  type: section
  label: Прочие данные
entities:
  - entity: sensor.kitchen_perception
  - entity: sensor.kitchen_pressure
  - entity: sensor.kitchen_heatindex
# End of code
```

---
