### ISSUE TITLE
Using the header toogle doesen't affect fold rows

### ISSUE THREAD

**Issue by Aura-Mancer** [thomasloven/lovelace-fold-entity-row#144]
My Home Assistant version: 2021.3.2

My lovelace configuration method (GUI or yaml): yaml

What I am doing: Using the header toogle to turn on and off all entities (lights in this case)

What I expected to happen: I expected the entities in the fold row to follow suit with the header toogle

What happened instead: The entities in the fold row didn't do anything when the header toggle was switched on an off

**Minimal** steps to reproduce: Create an entity card with some entities and a fold row, and set "show_header_toggle" to true. If you turn the header toggle on and off, the fold rows don't follow suit.

```yaml
# The least ammount of code possible to reproduce my error
type: entities
title: title
show_header_toggle: true
entities:
  - type: 'custom:fold-entity-row'
    head:
      entity: light.luces_del_cuarto_de_arturo
    entities:
      - entity: light.arturo_bulb1
      - entity: light.arturo_bulb2
      - entity: light.arturo_bulb3
  - entity: light.luces_del_ventilador_de_aura
# End of code
```

Demonstration:
![Image](https://i.imgur.com/tltTl81.gif) 

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
