### ISSUE TITLE
head entity doesn show state color

### ISSUE THREAD

**Issue by pdwonline** [thomasloven/lovelace-fold-entity-row#145]
My Home Assistant version: 2021.3.0

My lovelace configuration method (GUI or yaml): GUI

What I am doing:
Use fold entity card to group entities.
I added  ´state_color: true´ and expected the icons to color. This doesn't work for the 'head' entity but works for the unfolded entities.

```yaml
entities:
  - type: 'custom:fold-entity-row'
    head: group.lights_office
    group_config:
      state_color: true
    entities:
      - switch.wall_plug_switch_current_value_3
      - switch.wall_plug_switch_current_value_6
state_color: true
```

Error messages from the browser console:

---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
