### ISSUE TITLE
No graphics supported?

### ISSUE THREAD

**Issue by RaspiGame** [thomasloven/lovelace-fold-entity-row#147]
**My Home Assistant version** 
2021.3.4

**Fold-entity-row version (FROM BROWSER CONSOLE):** 20.0.4

**What I am doing: I try to a graphic entity**
What I expected to happen: Graph alone works, fold with switch work. But graphic inside the fold perform an error

**What happened instead:**
Error:
"Unknown type encountered: history-graph
type: history-graph
entities:
  - entity: sensor.mainpower_energy_today
    name: General
refresh_interval: 0
hours_to_show: 168"

**Minimal steps to reproduce**

```yaml
# The least ammount of code possible to reproduce my error

type: entities
entities:
  - type: custom:fold-entity-row
    head:
      type: section
    label: Label name
    entities:
      - type: history-graph
        entities:
          - entity: sensor.mainpower_energy_today
            name: General
        refresh_interval: 0
        hours_to_show: 168


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
`history-graph` is not an entities row. Try https://github.com/thomasloven/lovelace-hui-element

**Comment by RaspiGame** [comment]
Thank you for the answer @thomasloven !

I leave here an implementation's example in case anyone has the same doubt:
```yaml
type: 'custom:fold-entity-row'
head:
  type: section
  label: Daily
padding: 0
entities:
  - type: 'custom:hui-history-graph-card'
    card_type: vertical-stack
    entities:
      - entity: sensor.mainpower_energy_today
        name: General
    refresh_interval: 0
    hours_to_show: 168
```
