### ISSUE TITLE
Label get same color as background + now icon for head

### ISSUE THREAD

**Issue by elgeniskogen** [thomasloven/lovelace-fold-entity-row#148]
When I use the card with deafult light theme I see now label as it is written in same color as background. Also it would be great to be able to add an icon to the head.

Code used:
```
type: entities
entities:

  - type: 'custom:fold-entity-row'
    head:
      type: section
      label: Hvem har lagt seg?
    entities:
      - input_boolean.erik_lagt_seg
      - input_boolean.liv_lagt_seg

```
