### ISSUE TITLE
Filter-entity doesn't work

### ISSUE THREAD

**Issue by mikosoft83** [thomasloven/lovelace-fold-entity-row#152]
My Home Assistant version: 2021.4.5

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.4

_What I am doing:_ I added ```type: entity-filter``` in the ```entities:``` list of fold-entity-row card

_What I expected to happen:_ see the entity-filter. The entity-filter config works when I put it in a standalone card.

_What happened instead:_ Unknown type encountered: entity-filter

_**Minimal** steps to reproduce:_ as mentioned in "What I am doing"

```yaml
# The least ammount of code possible to reproduce my error

type: entities
entities:
  - type: 'custom:fold-entity-row'
    head: some.entity
    entities:
      - type: entity-filter
        entities:
          - some.entity
        state_filter:
          - on

# End of code
```

_Error messages from the browser console:_

row entity-filter Error: Unknown type encountered: entity-filter
    at d (chunk.1f510d4b62a23dbb7a38.js:formatted:5364)
    at c (chunk.1f510d4b62a23dbb7a38.js:formatted:5302)
    at Module.a (chunk.1f510d4b62a23dbb7a38.js:formatted:5494)
    at HTMLElement._createRow (fold-entity-row.js:1)
    at async Promise.all (index 0)
    at async https:/192.168.0.200:8123/hacsfiles/lovelace-fold-entity-row/fold-entity-row.js:1

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
