### ISSUE TITLE
Uncaught SyntaxError: Unexpected token 'export'

### ISSUE THREAD

**Issue by mhetzi** [thomasloven/lovelace-fold-entity-row#153]
My Home Assistant version: 2021.4.6

Fold-entity-row version (FROM BROWSER CONSOLE):
Error
Version from HACS: 20.0.4
What I am doing:

What I expected to happen:
   trying to use it
What happened instead:
![image](https://user-images.githubusercontent.com/5149682/116007885-2bd60300-a612-11eb-9f2f-3a08c4c828d7.png)

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

entities:
  - entity: switch.kuche
    icon: 'mdi:television-classic'
  - automation.switch_tv_kuche_off
  - automation.switch_tv_kuche_on
  - entity: switch.kuche_nintendo_switch
    icon: 'mdi:nintendo-switch'
  - entity: switch.kuche_raspberry
    icon: 'mdi:raspberry-pi'
  - entity: switch.kuche_shield
    icon: 'mdi:google-chrome'
  - entity: input_boolean.kueche_play_switch
    icon: 'mdi:nintendo-switch'
  - type: 'custom:fold-entity-row'
    head: switch.stereo_anlage_off
    entities:
      - switch.stereo_anlage_aux
state_color: true
title: Fernseher Küche
type: entities


```
# End of code
Error messages from the browser console:
fold-entity-row.js:42 Uncaught SyntaxError: Unexpected token 'export'

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
