### ISSUE TITLE
Remove entity card

### ISSUE THREAD

**Issue by hwikene** [thomasloven/lovelace-fold-entity-row#16]
Hi! is it possible to remove the entity card from poping up if you adjust entitys? 

![entity card](https://user-images.githubusercontent.com/17985923/49291710-869fba80-f4ab-11e8-8430-79379ef34765.jpg)

Here is me code: 
```
      - id: e68d6050eee94f82be8a174f6893b4d8  # Automatically created id
        type: vertical-stack
        cards:
          - type: custom:fold-entity-row
            head:
              type: section
              label: Modus
            items:
              - input_number.air_condition_temp
              - input_select.operation
              - input_select.fan
              - input_select.swing
```
