### ISSUE TITLE
Since 2021.05 update not displaying correctly

### ISSUE THREAD

**Issue by IronicBadger** [thomasloven/lovelace-fold-entity-row#163]
My Home Assistant version: 2021.05.4

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.4

What I am doing: Since updating to `2021.05` from `2021.04` the fold-entity-row portion of lovelace UI is not displaying correctly.

What I expected to happen:

What happened instead:

![image](https://user-images.githubusercontent.com/2773080/121280038-96ca5900-c8a3-11eb-95f6-1bb7f1c863f2.png)

**Minimal** steps to reproduce:

```yaml
entities:
  - entities:
      - light.lounge_table_lamp
      - light.lounge_bloom
      - light.rear_hallway
      - light.wled_kitchen_wetbar
      - light.tripod_spotlight
      - light.tripod_wooden
      - light.kitchen_counter_lights
      - light.kitchen_island_lights
    head:
      entity: light.downstairs_lights
      icon: mdi:lightbulb-group
      label: Downstairs Lights
    type: custom:fold-entity-row
title: All Lighting
type: entities

```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
