### ISSUE TITLE
Setting correct name and icon

### ISSUE THREAD

**Issue by jamiekris** [thomasloven/lovelace-fold-entity-row#164]
Trying to setup a fold entity row, however, no matter where I enter a 'name' and 'icon', I get only the defaults. Below is how my configuration looks. I always seem to get 'Kitchen Lights' and the default light group icon at the head of this row.

```
type: entities
entities:
  - entity: light.kitchen_lights
    name: Kitchen
    icon: fas:pizza-slice
    type: custom:fold-entity-row
    head:
      entity: light.kitchen_lights     
    group_config:
      icon: fas:pizza-slice
    entities:
      - light.kitchen_1
      - light.kitchen_2
      - light.kitchen_3
      - light.kitchen_4
      - light.kitchen_5
      - light.kitchen_6
```

**Comment by thomasloven** [comment]
It should go together with everything else that has to do with the `head` row, like in 8/10 of the usage examples in the readme.

Please use the issue template

**Comment by jamiekris** [comment]
Thanks for the response, but changing it to below, does not change the final outcome, it still shows the capitalized form of the entity name (not what I specify in name) and the default icon. What am I missing here?

```

type: entities
entities:
  - entity: light.kitchen_lights
    type: custom:fold-entity-row
    head:
      entity: light.kitchen_lights
      name: Kitchen
      icon: fas:pizza-slice
    group_config:
      icon: fas:pizza-slice
    entities:
      - light.kitchen_1
      - light.kitchen_2
      - light.kitchen_3
      - light.kitchen_4
      - light.kitchen_5
      - light.kitchen_6
```

**Comment by thomasloven** [comment]
Try removing the top `entity: light.kitchen_lights`.

`entity:` overrides `head:` for things to work with auto-entities.

**Comment by jamiekris** [comment]
Yes. This was the solution.
```

type: entities
entities:
  - type: custom:fold-entity-row
    head:
      entity: light.kitchen_lights
      name: Kitchen
      icon: fas:pizza-slice
    group_config:
      icon: fas:pizza-slice
    entities:
      - light.kitchen_1
      - light.kitchen_2
      - light.kitchen_3
      - light.kitchen_4
      - light.kitchen_5
      - light.kitchen_6
```
