### ISSUE TITLE
Icon out of position.

### ISSUE THREAD

**Issue by Tuschz** [thomasloven/lovelace-fold-entity-row#165]
My Home Assistant version: 2021.6.5

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.4

What I am doing:

I am using custom:fold-entity-row wrapped in custom:auto-entities

What I expected to happen:

I expected the icon to stay on the same line as the entity and the entity information / action

What happened instead:

The icon shifted to the line above

![image](https://user-images.githubusercontent.com/49319153/122347557-71e08080-cf4a-11eb-99a3-571c0b741a74.png)

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

type: custom:auto-entities
card:
  type: custom:fold-entity-row
  head:
    type: section
    label: Skab
filter:
  include:
    - area: Skab
  exclude:
    - state: unavailable
    - domain: sensor
    - domain: vacuum
    - domain: switch
    - domain: binary_sensor
sort:
  method: domain
  reverse: false
show_empty: false

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
