### ISSUE TITLE
clickable: true does not respond to touch

### ISSUE THREAD

**Issue by amitkeret** [thomasloven/lovelace-fold-entity-row#167]
My Home Assistant version: 2021.6.6

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.4

What I am doing: tapping the header (on a mobile device HA app), after configuring `clickable: true`

What I expected to happen: the folded entities should be revealed

What happened instead: "entity info" is shown (default action when tapping on entities in the HA app)

**Minimal** steps to reproduce: as above; create fold, set `clickable: true`, tap on row header

```yaml
# The least ammount of code possible to reproduce my error
type: custom:fold-entity-row
clickable: true
head:
  entity: light.living_room
  icon: mdi:sofa
entities:
  - entity: light.light_switch_01
    name: Floor lamp (TV area)
  - entity: light.light_switch_02
    name: Floor lamp (play area)
# End of code
```

Error messages from the browser console: N/A

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
