### ISSUE TITLE
request: add option show_last_changed to head: group.groupname 

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#17]
HI,

Implementing you very nice card, I tried the last_changed on the items in the group, as you have with separate entities.

```
    group_config:
      secondary_info: last-changed

```

This seems to work ;-) maybe add it to the documentation?

Id like to ask If you could make it a global option for the main group, which would take out many the same lines:

instead of:

```
  - type: entities
    title: Folding entities
    entities:
      - type: custom:fold-entity-row
        head: group.bureau_lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.office_lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.guest_room_lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.hallway_lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.library_lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.hobby_corner_lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.gamers_den_lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.kantoor_lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.gym_lights
        group_config:
          secondary_info: last-changed

```

we could have:

```
  - type: entities
    title: Folding entities
    group_config:
      secondary_info: last-changed
    entities:
      - type: custom:fold-entity-row
        head: group.bureau_lights
      - type: custom:fold-entity-row
        head: group.office_lights
      - type: custom:fold-entity-row
        head: group.guest_room_lights
      - type: custom:fold-entity-row
        head: group.hallway_lights
      - type: custom:fold-entity-row
        head: group.library_lights
      - type: custom:fold-entity-row
        head: group.hobby_corner_lights
      - type: custom:fold-entity-row
        head: group.gamers_den_lights
      - type: custom:fold-entity-row
        head: group.kantoor_lights
      - type: custom:fold-entity-row
        head: group.gym_lights
```

second: if a group contains a group ( example, I have a group with 2 groups of lights) the main group says 'on' but doesn't show a toggle, which would be very handy indeed. Please consider adding that?

![schermafbeelding 2018-12-03 om 21 27 12](https://user-images.githubusercontent.com/33354141/49399677-3a21dc80-f742-11e8-8d58-6899f917ae7b.jpg)

Group Bureau:
![schermafbeelding 2018-12-03 om 21 28 05](https://user-images.githubusercontent.com/33354141/49399716-5de52280-f742-11e8-83c3-3f2440dacb7b.jpg)

Group Office
![schermafbeelding 2018-12-03 om 21 28 13](https://user-images.githubusercontent.com/33354141/49399733-68072100-f742-11e8-8ad6-abb8175a6b60.jpg)

this is regular HA:

![schermafbeelding 2018-12-03 om 21 36 31](https://user-images.githubusercontent.com/33354141/49400119-9802f400-f743-11e8-9509-5a9e12ee5222.jpg)

btw, please note the informative last_changed below the groups also, would be great to have in your card as well!
Thanks for considering.
