### ISSUE TITLE
How do I add a picture-entity?

### ISSUE THREAD

**Issue by DivanX10** [thomasloven/lovelace-fold-entity-row#170]
How do I write the code so that the collapse of the buttons with the image works?

![image](https://user-images.githubusercontent.com/64090632/126779502-cb8b4124-9499-4232-9179-05457c7e5165.png)

If I do this, then I will have a round icon and a slider, and I need graphic buttons
```
type: vertical-stack
cards:
  - type: custom:fold-entity-row
    head:
      type: section
      label: Manual operation
    open: true
    entities:
      - image: \local\photo\person_01.jpg
        entity: input_boolean.virtual_tracing_person
        name: Person
        show_state: false
        show_name: false
        tap_action:
          action: call-service
          service: input_boolean.toggle
        service_data: null
        target:
          entity_id: input_boolean.virtual_tracing_person
        hold_action:
          action: more-info
        aspect_ratio: '0'
```
