### ISSUE TITLE
Folded row entities not recognised as light entities / Friendly names cannot be overwritten in workaround

### ISSUE THREAD

**Issue by gith-account** [thomasloven/lovelace-fold-entity-row#171]
My Home Assistant version: 2021.7.3

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.4

What I am doing:

I am using fold-entity-row on a lovelace card that shows lights in a room.

```yaml
cards:
  - type: entities
    entities:
      - entity: light.sofa
      - type: custom:fold-entity-row
        head:
          entity: light.table_group
          name: table
      - type: custom:fold-entity-row
        head:
          entity: light.bookshelf_group
          name: bookshelf
    title: livingroom
```

What I expected to happen:

Usually, a header toggle appears on cards with multiple light entities to toggle all light entities on the card. I expected to see a header toggle next to the "livingroom" header that switches light.sofa, light.table_group, and light.bookshelf_group

What happened instead:

The custom fold-entity-row entities are not recognised as lights on the room level and the room is considered to only have one light (sofa). Accordingly, the expected header toggle next to “livingroom” is not shown and, if forced to show (“show_header_toggle: true”), only switches the sofa light.

Workaround / What I am doing:

```yaml
cards:
  - type: entities
    entities:
      - entity: light.sofa
      - entity: light.table_group
        name: table
        type: custom:fold-entity-row
        head:
          entity: light.table_group
          name: table
      - entity: light.bookshelf_group
        name: bookshelf
        type: custom:fold-entity-row
        head:
          entity: light.bookshelf_group
          name: bookshelf
    title: livingroom
```

This fixes the above mentioned problem. However, with the following new problem:

What I expected to happen:

The friendly name of the light groups should be overwritten.

What happened instead:

Friendly names are not overwritten (tried in two locations in the above code, it fails in both).

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

cards:
  - type: entities
    entities:
      - entity: light.sofa
      - entity: light.table_group
        name: table
        type: custom:fold-entity-row
        head:
          entity: light.table_group
          name: table
    title: livingroom

# End of code
```

Error messages from the browser console:

no relevant error messages found

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
