### ISSUE TITLE
Header entity not respecting state_color

### ISSUE THREAD

**Issue by soloam** [thomasloven/lovelace-fold-entity-row#172]
My Home Assistant version: 2021.7.1

Fold-entity-row version: 20.0.4

What I am doing:

When in the entities card the state_color is set to true, the header does not reflect that state.

What I expected to happen:

When in the entities card the state_color is set to true, the header should change color based on state. Also the child's  should reflect this option (from what I can tell, the header never changes color, even with the option to true).

What happened instead:

When in the entities card the state_color is set to true, the header does not reflect that state.

**Minimal** steps to reproduce:

```yaml
type: entities
entities:
  - type: custom:fold-entity-row
    head: group.livingroom_lights
    group_config:
      secondary_info: last-changed
title: Livingroom Lights
state_color: true
```
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
