### ISSUE TITLE
Expand based on state

### ISSUE THREAD

**Issue by retroneo** [thomasloven/lovelace-fold-entity-row#173]
It would be great to expand automatically to show more info based on the state of something hidden

(e.g. expand to show which drive in a nine bay NAS has a high temperature.)

So I could have it hidden normally, but it would be expanded automatically if any listed conditions are met.

**Comment by robbinonline** [comment]
This feature will be awesome!

**Comment by KrX3D** [comment]
+1

**Comment by rhoriguchi** [comment]
An example use case:

```yaml
type: custom:fold-entity-row

head:
  entity: sensor.ipv4_address_wlan0
  name: wlan0
  icon: mdi:web

open: '{{ not is_state(''sensor.ipv4_address_wlan0'', ''unknown'') }}'

entities:
- entity: sensor.network_throughput_in_wlan0
  name: Down
  icon: mdi:download
- entity: sensor.network_throughput_out_wlan0
  name: Up
  icon: mdi:upload
  ````
