### ISSUE TITLE
Add aria-hiden for screen readers

### ISSUE THREAD

**Issue by Nardol** [thomasloven/lovelace-fold-entity-row#176]
My Home Assistant version: 2021.8.8

Fold-entity-row version (FROM BROWSER CONSOLE): sory, not really accessible with screen reader

What I am doing:
I want to hide some input_number to avoid changing values accidentaly so I put these entities to a fold-entity-row and set open to false

What I expected to happen:
These entities should not be used at all except if I open the block

What happened instead:
I can change values as my screen reader cannot know they are hidden. Moreover, the button to hide/show entities is not recognized at all so I have to guess where to click even with `clickable: true`
A good beginning: https://stackoverflow.com/questions/38994550/how-to-hide-overflow-content-from-screenreaders

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
- type: entities
  entities:
    - type: custom:fold-entity-row
      head:
        type: section
        label: Tarifs
      open: false
      clickable: true
      entities:
        - input_number.tarif_hp
        - input_number.tarif_hc

# End of code
```

Error messages from the browser console:
Same as the version, it is very difficult to use browser console with a screen reader in every browser.

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
