### ISSUE TITLE
Ability to set custom name on fold-entity-row

### ISSUE THREAD

**Issue by FlyersPh9** [thomasloven/lovelace-fold-entity-row#178]
I would like the ability to set a custom name on a `custom:fold-entity-row`.  How I would expect it to work:
```
entities:
  - type: custom:fold-entity-row
    head: group.living_room_lights
	name: Lights
```
Otherwise I end up with this redundancy:
![Screen Shot 2021-10-11 at 11 39 32 PM](https://user-images.githubusercontent.com/849817/136887384-fc298196-e707-45a6-8b71-0bd45c7bf28f.png)
