### ISSUE TITLE
Customizable icon for expand&close // expand&close by a other entity // Icon position

### ISSUE THREAD

**Issue by YvesZH** [thomasloven/lovelace-fold-entity-row#179]
I use some of your Lovelace tools and I am grateful for your great work. Without you my lovelace pannel would be a mess. Now I have a idea as an extension for this row addon:
 
- Folder expand or closed by default, can be made dependent on any entitiy (if a condition is true). This is only a default value and can be overridden using the expand-button.
**Setup idea :**
```
type: entities
entities:
  - type: custom:fold-entity-row
    open: entity
       condition_entity: light.ceiling_light
       condition_state: "on"
    entities:
      - light.bed_light
```

- A setting would be great where the expand-button could also be displayed to the left of the 'switch'
![a_swap](https://user-images.githubusercontent.com/64573990/138765865-457ddcb0-c611-47e7-ae56-72e7eda285b4.JPG)

- Customizable icon for expand / close (overwrites the default expand-button). A different icon and/or color for both states.
**Example close:** (the expand-button is in this example to the left of the switch)
![a_off](https://user-images.githubusercontent.com/64573990/138765837-b6f9e328-3b17-484a-99d9-cd96846b58d3.jpg)
**Example expand:** (the expand-button changes to yellow after pressing)
![a_on](https://user-images.githubusercontent.com/64573990/138765839-12274a4f-b2c3-4cba-a82f-2531a4fc122a.jpg)

I hope this is not too complicated and I was able to motivate you for this idea
Thanks a lot
