### ISSUE TITLE
Long header name

### ISSUE THREAD

**Issue by hekm77** [thomasloven/lovelace-fold-entity-row#18]
If I use a long header name:
```
type: entities
entities:
    - type: custom:fold-entity-row
       head: group.light_auto_status
```

Desktop view
<img width="419" alt="3" src="https://user-images.githubusercontent.com/22895433/49430537-8c4b1800-f7ab-11e8-9575-f92b3fe0df06.png">
Mobile view
<img width="324" alt="4" src="https://user-images.githubusercontent.com/22895433/49430564-9ec55180-f7ab-11e8-81d4-60090157f5c2.png">
