### ISSUE TITLE
Light group with 1 light issue

### ISSUE THREAD

**Issue by SeLLeRoNe** [thomasloven/lovelace-fold-entity-row#180]
My Home Assistant version: 2021.10.6

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.4

What I am doing:
- Using state-switch to hide card when state not on and not off
- Using decluttering card in the above to have things cleaned up
- Using entity-fold-row inside entity which load card from decluttering card

What I expected to happen:
To show all the lights on a per-room basis

What happened instead:
All works except for 1 light group, can't figure out the root cause

**Minimal** steps to reproduce:
I'll provide the code, I honestly not sure how to reproduce, it only happen for a specific "room"

state-card
```yaml
# The least ammount of code possible to reproduce my error
      - type: custom:state-switch
        entity: light.patio_lights
        states:
          "on":
            type: custom:decluttering-card
            template: patio_lights_fold
          "off":
            type: custom:decluttering-card
            template: patio_lights_fold
# End of code
```

decluttering-card
```yaml
# The least ammount of code possible to reproduce my error
---
patio_lights_fold:
  card:
    type: entities
    entities:
      - type: custom:fold-entity-row
        head:
          type: custom:slider-entity-row
          entity: light.patio_lights
          name: Patio
          toggle: true
          hide_state: true
          hide_when_off: false
          full_row: false
          min: 0
          max: 100
          step: 1
        entities:
          - type: custom:decluttering-card
            template: light_card_rgb
            variables:
              - name: Wall Light
              - entity: light.patio_led1624g9_wall

# End of code
```

light-card
```yaml
# The least ammount of code possible to reproduce my error
---
light_card_rgb:
  card:
    type: custom:state-switch
    entity: '[[entity]]'
    states:
      "off":
          type: 'custom:slider-entity-row'
          entity: '[[entity]]'
          name: '[[name]]'
          toggle: true
          hide_state: true
          hide_when_off: false
          full_row: false
          min: 0
          max: 100
          step: 1
      "on":
        type: entities
        show_header_toggle: false
        entities:
          - type: 'custom:slider-entity-row'
            entity: '[[entity]]'
            name: '[[name]]'
            toggle: true
            hide_state: true
            hide_when_off: false
            full_row: false
            min: 0
            max: 100
            step: 1
          - type: 'custom:rgb-light-card'
            entity: '[[entity]]'
            size: 25
            colors:
              - rgb_color:
                - 255
                - 255
                - 255
                icon_color: '#FFFFFF'
              - rgb_color:
                - 0
                - 00
                - 255
                icon_color: '#0000FF'
              - rgb_color:
                - 0
                - 255
                - 0
                icon_color: '#00FF00'
              - rgb_color:
                - 255
                - 0
                - 0
                icon_color: '#FF0000'
              - rgb_color:
                - 255
                - 0
                - 255
                icon_color: '#FF00FF'
              - rgb_color:
                - 255
                - 102
                - 0
                icon_color: '#FF6600'
              - rgb_color:
                - 255
                - 255
                - 0
                icon_color: '#FFFF00'

# End of code
```

Error messages from the browser console:
None that I can see that are directly related.
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
