### ISSUE TITLE
Lines outside the card

### ISSUE THREAD

**Issue by kksligh** [thomasloven/lovelace-fold-entity-row#186]
My Home Assistant version: 2021.11.2

Fold-entity-row version (FROM BROWSER CONSOLE):  20.0.9

What I am doing:  Since I updated to the latest core version, all my lovelace cards show lines outside the box on the folds.  There's no action as this is a cosmetic issue.  I use this card quite a bit in my dashboards, and I can confirm its doing it with all cards.

What I expected to happen:  I expect the lines to stay within the card like it was before.

What happened instead:  See image attached

![line outside card example](https://user-images.githubusercontent.com/83232851/140958534-0219e3d8-fe42-4499-8d7e-7d66fd191031.jpg)

**Minimal** steps to reproduce:  I'm attaching example code but from what I can tell, just have the latest core version and it breaks the visual.  I could be wrong here, but this was not an issue until after the update this AM.

```yaml
# The least amount of code possible to reproduce my error
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      type: section
      label: TV Remote
    padding: 0
    entities:
      - type: custom:roku-card
        entity: media_player.kids_bedroom_tv_tcl_roku
        tv: true
        apps:
          - icon: mdi:netflix
            app: Netflix
          - icon: mdi:amazon
            app: Prime Video
          - icon: mdi:castle
            app: Disney Plus
          - icon: mdi:hulu
            app: Hulu
        name: Kids Bedroom TV
  - type: custom:fold-entity-row
    head:
      type: section
      label: Sonos
    padding: 0
    entities:
      - type: custom:mini-media-player
        entity: media_player.kids_bedroom_sonos
        group: true
        tts:
          platform: cloud
        hide:
          controls: false
          shuffle: false
        speaker_group:
          platform: sonos
          show_group_count: true
          entities:
            - entity_id: media_player.basement_sonos
              name: Sonos Basement
            - entity_id: media_player.kids_bedroom_sonos
              name: Sonos Kids Bedroom
            - entity_id: media_player.kids_playroom_sonos
              name: Sonos Kids Playroom
            - entity_id: media_player.kitchen_sonos
              name: Sonos Kitchen
            - entity_id: media_player.living_room_sonos
              name: Sonos Living Room
            - entity_id: media_player.master_bedroom_sonos
              name: Sonos Master Bedroom
            - entity_id: media_player.master_bathroom_sonos
              name: Sonos Master Bathroom
            - entity_id: media_player.study_sonos
              name: Sonos Study
            - entity_id: media_player.garage_move_1_sonos
              name: Sonos Move 1
            - entity_id: media_player.outdoors_move_2_sonos
              name: Sonos Move 2
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- X Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- X Have made sure I am using the latest version of the plugin.
- X Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- X Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
