### ISSUE TITLE
group_config no longer working with state_color

### ISSUE THREAD

**Issue by gvssr** [thomasloven/lovelace-fold-entity-row#187]
My Home Assistant version: 2021.11.2

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.9

What I am doing: applying state_color: true to the group_config

What I expected to happen: entities in the group should show their state_color when on/enabled/active

What happened instead: no state_color is applied

**Minimal** steps to reproduce:
* Add group_config: state_color: true
* Make the entities active

```yaml
# The least ammount of code possible to reproduce my error
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      entity: primary_entity
      secondary_info: last-changed
      state_color: true
    group_config:
      secondary_info: last-changed
      state_color: true
    entities:
      - secondary_entity
      - secondary_entity
# End of code
```

![image](https://user-images.githubusercontent.com/61377476/140966898-fe117c23-aa56-4814-945c-01270c21e8d3.png)

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
