### ISSUE TITLE
Mouse over information hidden behind "fold"

### ISSUE THREAD

**Issue by scaarup** [thomasloven/lovelace-fold-entity-row#189]
My Home Assistant version: 2021.11.4

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.11

What I am doing:
Holding mouse button while using a slider control.

What I expected to happen:
I expect to be able to see the value of the slider

What happened instead:
The pop-up information from the slider is hidden behind the "head" fold entity

![image](https://user-images.githubusercontent.com/8055470/141978462-2661bd4b-afd3-48e8-b95d-ec81a17c3b5f.png)

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
type: grid
square: false
columns: 1
cards:
  - type: entities
    entities:
      - type: custom:fold-entity-row
        head:
          entity: input_boolean.heating_schedule_frederik
          name: Tidsplan
          state_color: true
        entities:
          - entity: input_number.heating_target_temp_plan_frederik
            icon: mdi:clock-outline
            name: Temp. dagstid
          - entity: input_number.heating_target_temp_noplan_frederik
            name: Temp. nat
    title: Tidsplan, Frederik
    show_header_toggle: false

# End of code
```

Error messages from the browser console:
n/a
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
