### ISSUE TITLE
State not updating

### ISSUE THREAD

**Issue by houtknots** [thomasloven/lovelace-fold-entity-row#19]
I'm having the same problem as @Aephir [https://jhcs.xyz/xcDDS](https://jhcs.xyz/xcDDS)
Below I have put my configuration if you want any more info please let me know.

Home-Assistant running on Hass.io version 0.83.3
I ain't getting any errors in the Home-Assistant log

Import plugin in lovelace:
```yaml
resources:
  - url: /local/lovelace/fold-entity-row.js
    type: js
```

The card config:
```yaml     
      - id: 9d5d9ea367sb6dfg48a580d2asdfa345fgh3521241234
        title: Kamers
        type: entities
        entities:
          - type: custom:fold-entity-row
            head: group.room1
            items:
              - switch.spots
              - switch.circle
              - switch.ledstripsbureau
              - switch.ledstripbed
              - switch.bedlamp
              - switch.onairlamp
              - switch.jayce_wereldbol
              - type: custom:fold-entity-row
                head: cover.front
                items:
                  - input_datetime.rolluikweekdayopen
                  - input_datetime.rolluikweekdaydicht
                  - input_datetime.rolluikweekendopen
                  - input_datetime.rolluikweekenddicht
          - type: custom:fold-entity-row
            head: group.zolder
            items:
              - type: custom:fold-entity-row
                head: cover.zolder
                items:
                  - input_datetime.rolluikzlopen
                  - input_datetime.rolluikzldicht
                  - input_datetime.rolluikzlopenmiddag
                  - input_datetime.rolluikzlsluitvoorzon
                  - input_boolean.zolderzlsluitvoorzon
```
