### ISSUE TITLE
Logbook

### ISSUE THREAD

**Issue by julienlarivee** [thomasloven/lovelace-fold-entity-row#190]
I can't seem to get it work with a logbook.
Would it be possible to add this feature?

Here is my code:
```
type: entities
entities:
  - entity: binary_sensor.detecteur_de_mouvement_entree
    name: Mouvement
  - type: custom:fold-entity-row
    head:
      type: section
      label: Journal
    entities:
      - type: logbook
        entities:
          - binary_sensor.detecteur_de_mouvement_entree
title: Entrée
```
And what's the error:
![image](https://user-images.githubusercontent.com/55027006/142078798-ffc18fd2-9e32-45c5-bf77-6db3094f8fd8.png)
