### ISSUE TITLE
card_mod not applied if "open: false"

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-fold-entity-row#191]
My Home Assistant version: 2021.11.4

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.11

What I am doing:
apply a `card-mod` style for folded items

What I expected to happen:
the style is applied

What happened instead:
the style is applied only if `open: true`

**Minimal** steps to reproduce:
```yaml
type: entities
title: card_mod & open
card_mod:
  style:
    fold-entity-row:
      $:
        div#items hui-text-entity-row:
          $: |
            hui-generic-entity-row {
              color: red;
            }
entities:
  - type: custom:fold-entity-row
    open: true
    padding: 0
    head:
      entity: sun.sun
    entities:
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
  - type: custom:fold-entity-row
    open: false
    padding: 0
    head:
      entity: sun.sun
    entities:
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
```
![image](https://user-images.githubusercontent.com/71872483/142657447-dbb69c20-ed84-4227-8112-d4b97605237a.png)

Error messages from the browser console:
no errors related to the card

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
