### ISSUE TITLE
last entity in list is clipped

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#192]
HA 2021.11.3
Fold-entity-row 20.0.12

but there's 1 thing happening now: on folds with the entities listed verbosely, the bottom entity is not getting all the vertical space it should and is clipped. With a simple icon/entity/state all on 1 line that is diffult to see (though noticeably less height is displayed below the entity and above the next fold):

<img width="412" alt="Schermafbeelding 2021-11-20 om 13 21 43" src="https://user-images.githubusercontent.com/33354141/142726109-a0424ed6-f566-4ad4-a28b-f243017b2566.png">

but when using entity_picture, 

<img width="408" alt="Schermafbeelding 2021-11-20 om 13 20 00" src="https://user-images.githubusercontent.com/33354141/142726050-d7fb10bb-0d52-466f-acef-d7b22cc2fbbc.png">

yaml:
```
  - type: custom:fold-entity-row
    head:
      type: section
      label: Legacy
    padding: 0
    entities:
      - device_tracker.znorra_oud_app
      - device_tracker.telefoon_app
 ```

or secondary_info 

<img width="413" alt="Schermafbeelding 2021-11-20 om 13 24 54" src="https://user-images.githubusercontent.com/33354141/142726201-37765c4b-604b-407a-aae5-1bedddbe13ee.png">

or double lined unit, it becomes clear immediately:

<img width="400" alt="Schermafbeelding 2021-11-20 om 12 33 44" src="https://user-images.githubusercontent.com/33354141/142726020-8b4b06c8-2295-4fe0-9bfa-951c7b6711d3.png">

yaml for this is plain:
```
  - type: custom:fold-entity-row
    head:
      type: section
      label: Details
    padding: 0
    entities:
      - entity: sensor.family_home
        secondary_info: last-changed
      - entity: group.family
        secondary_info: last-changed
      - type: divider
      - entity: binary_sensor.daughters_home
        secondary_info: last-changed
      - etc etc
      - type: custom:slider-entity-row
        entity: input_number.presence_timer
```

this doesnt happen when using auto-entities in the fold..

_Originally posted by @Mariusthvdb in https://github.com/thomasloven/lovelace-fold-entity-row/issues/191#issuecomment-974642411_

**Comment by Mariusthvdb** [comment]
Ive tries to add a margin to the div#items with:
```
    card_mod:
      style: |
        div#items {
          margin: 0px 0px 16px 0px;
        }
```

but as you can see that is indeed applied, and still the last entity is clipped:

<img width="505" alt="Schermafbeelding 2021-12-07 om 17 05 43" src="https://user-images.githubusercontent.com/33354141/145064285-20755b54-8c78-4cbd-a214-53c911e5586b.png">

**Comment by Mariusthvdb** [comment]
seems this is a Safari thing....


In Chrome the issue isnt showing.

<img width="512" alt="Schermafbeelding 2021-12-15 om 14 06 46" src="https://user-images.githubusercontent.com/33354141/146191894-d2693428-e961-4229-91b7-311f563cf89a.png">

btw, I did play around with https://github.com/thomasloven/lovelace-fold-entity-row/blob/f7870a2616659b408a3616665f2d7e05882655a3/src/main.ts#L375 but that doesnt really do anything in Safari. In Chrome it actually adds to the whitespace after the last child, but that is not is needed ofc..

So still happening on 2022.1.0.dev20211215

**Comment by Mariusthvdb** [comment]
sorry bout that, wrong button pressed

**Comment by Mariusthvdb** [comment]
downgrade to 20011 fixes the issue right away, so I figured it might be the
```
      #measure > *:last-child {
        margin-bottom: 0;
      }
```

and commented that in the latest resource, but unfortunately that alone doesn't fix it. So for now, my solution is to install 20011 and hoe not to see any other glitches you fixed in the later versions.

Hope this will give you leads on how to fix it in a patch version, thanks!

**Comment by thomasloven** [comment]
Please try 20.0.13

**Comment by Mariusthvdb** [comment]
thanks!
seems the last item is no longer clipped, but the slide out is really odd. entities 'shine through' while opening. Folding in has the reversed effect, entities remain visible briefly while the card has been folded in

I had commented the line
```
        /*transition: max-height 0.2s ease-in-out;*/
```
 in the former release, so to make the fold react more swiftly, and tried that now too, but that doesnt really help the visual effect above.

**Comment by thomasloven** [comment]
Should be fixed now.
I also added a `no_animation` option.

**Comment by Mariusthvdb** [comment]
clipping seems fixed, animation (no option set yet) seems very off still.

![Jan-28-2022 13-41-37](https://user-images.githubusercontent.com/33354141/151549021-b5b0950e-bef9-44c6-b7f5-c35ec561aaea.gif)

using the new no_animation : true: perfect!

![Jan-28-2022 13-50-59](https://user-images.githubusercontent.com/33354141/151550173-c77d0be2-6884-4867-97dd-0fdbd9c99352.gif)

btw, did you ever consider setting a global option on the fold? Or would you accept a FR to do so?

Use case, I use `padding: 0` on each card, and would also use the no animation on each card. I card_mod the fold label to use
```
  - type: custom:fold-entity-row
    head:
      type: section
      label: Details
      card_mod:
        style: |
          .label {
            margin-left: 0px;
          }
```
to align , so its getting a bigger config everywhere:

```
  - type: custom:fold-entity-row
    head:
      type: section
      label: Details
      card_mod:
        style: |
          .label {
            margin-left: 0px;
          }
    padding: 0
    no_animation: true
```

would there be any chance of setting that globally for all folds? the card_mod maybe get its own config option and be
```
  - type: custom:fold-entity-row
    head:
      type: section
      label: Details
    margin: 0
    padding: 0
    no_animation: true
```

and set those globally?
