### ISSUE TITLE
add show_empty: config option

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#193]
using eg:

```
      - type: custom:fold-entity-row
        head:
          type: section
          label: Disconnected
        padding: 0
        show_empty: false # <<------
        entities:

          - type: custom:auto-entities
            card:
              type: entities
              card_mod: *mod
            show_empty: false
            filter:
              include:
                - entity_id: sensor.*_connectivity
                  state: disconnected
```

would allow us to have the fold only show when in fact entities are available to display. I've played with a conditional , but that requires another additional binary_sensor in the backend
