### ISSUE TITLE
Unfolding shows all entities before the animation starts

### ISSUE THREAD

**Issue by julienlarivee** [thomasloven/lovelace-fold-entity-row#196]
My Home Assistant version: 2021.11.5

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.12

What I am doing: Unfolding a row.

What I expected to happen: Showing the entities inside the fold one by one as the animation goes down.

What happened instead: All the entities inside the fold appears, then the fold animation starts.

Here is a printscreen during the unfolding with the entity repeated a couple of time so it can be easyer to see:
![12](https://user-images.githubusercontent.com/55027006/144664871-eee66e18-040b-4bba-a6f0-e8f95bdcd387.png)

**Minimal** steps to reproduce: Unfolding a row. Having many entities in the fold-entity-row may help to see it.

```yaml
type: entities
entities:
  - automation.avertissement_lavage_termine
  - type: custom:fold-entity-row
    head:
      type: section
      label: Paramètres
    entities:
      - input_number.temps_lavage_termine
title: Salle de lavage
show_header_toggle: false
```

Error messages from the browser console: None

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
What browser are you using?

**Comment by julienlarivee** [comment]
Google chrome 
Version 96.0.4664.45 (Build officiel) (64 bits)

**Comment by fotis3d** [comment]
I confirm this is happening to me too.

**Comment by Shamshala** [comment]
Same here

**Comment by ildar170975** [comment]
have to confirm the issue.
Win10x64, Chrome

**Comment by mikosoft83** [comment]
Vivaldi user (chromium based) gone through several updates, Edge as well. I'm using folds extensively and every single one does it.

**Comment by thomasloven** [comment]
Please try 20.0.13

**Comment by fotis3d** [comment]
There is a new version ? I will try as soon as HACS prompts me. :). Thanks.

**Comment by mikosoft83** [comment]
> Please try 20.0.13

Just tested, works as expected! Great work as always, Thomas

**Comment by julienlarivee** [comment]
@thomasloven works great on the first fold, but is still there with nested fold.
On 20.0.13 and cache cleared.

Here is an example:
```
type: entities
entities:
  - entity: input_boolean.gerer_panne_electrique
    name: Électrique
  - entity: input_boolean.gerer_panne_internet
    name: Internet
  - type: custom:fold-entity-row
    head:
      type: section
      label: Paramètres
    entities:
      - type: custom:fold-entity-row
        head:
          type: section
          label: Électrique
        entities:
          - entity: input_number.temps_verification_panne_electrique
            name: Temps de vérification
      - type: custom:fold-entity-row
        head:
          type: section
          label: Internet
        entities:
          - entity: input_number.temps_verification_panne_internet
            name: Temps de vérification
title: Pannes
show_header_toggle: false
```
The sections "Électrique" and "Internet" are still doing it.
