### ISSUE TITLE
fold-entity-row not displayed properly on iPhone

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-fold-entity-row#198]
My Home Assistant version: 2021.11.5

Fold-entity-row version (FROM BROWSER CONSOLE):
2.0.12

What I am doing:
Open a page on iPhone 5S (12.5.5).

What I expected to happen:
The `fold-entity-row` is displayed as well as other cards on the page.

What happened instead:
The card is not displayed properly.
Other cards on the page are not displayed at all.
![изображение](https://user-images.githubusercontent.com/71872483/145665433-7b624371-2ee1-418e-b488-b994ab2ffeb0.png)

**Minimal** steps to reproduce:
1. Create a view.
2. Place this card on the view as the 1st card:
```
type: entities
entities:
  - type: custom:fold-entity-row
    open: false
    padding: 0
    head:
      entity: input_boolean.test_boolean
    entities:
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
```
Picture from a PC:
![изображение](https://user-images.githubusercontent.com/71872483/145665349-bed61c36-085c-494c-a798-6d25cdc11ea3.png)

3. Place other cards on the view.

Error messages from the browser console:
no messages related to the card.

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Have to admit that ALL fold-entity-row (not only with toggles) are displayed in a wrong way (like it was described in the 1st post) sometimes.
Sometimes I can fix it by erasing a cache, it helps but not always.

**Comment by antsar** [comment]
I believe I'm seeing this same issue on an iPad Air 1 running iOS 12.5.5, using fold-entity-row 20.0.12 on Home Assistant 2021.12.10. It happens in both the Home Assistant app, and in Safari. I believe the fold-entity-row may have loaded correctly once or twice after a huge delay (or possibly a reload), but I can't get it to work consistently.

Attaching Web Inspector to Safari on the iPad turns up the following errors.

```
(2x) [Error] Unhandled Promise Rejection: ReferenceError: Can't find variable: ResizeObserver    - fold-entity-row.js:931
[Error] Unhandled Promise Rejection: ReferenceError: Can't find variable: ResizeObserver           - fold-entity-row.js:276
[Error] Unhandled Promise Rejection: ReferenceError: Can't find variable: ResizeObserver           - fold-entity-row.js:931
```

The same configuration works perfectly on desktop browsers, as well as an iPad Pro running iOS 15.1. The newer iPad also does not produce those ReferenceErrors in the log.

**Comment by thomasloven** [comment]
Should be fixed in 20.0.13

**Comment by ildar170975** [comment]
Found another (very different) issue on iPhone 5S (iOS 12.5.5).
1. Create a new tab.
2. Add this card:
```
type: entities
entities:
  - type: custom:fold-entity-row
    open: false
    padding: 0
    head:
      entity: input_boolean.test_boolean
    entities:
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
```
3. It look like this:
![image](https://user-images.githubusercontent.com/71872483/151631188-e213bcf9-85ef-4416-b6df-1f3dff4d60df.png)

4. To reproduce the glitch -go to another tab and refresh it (swipe down).
Go back to the 1st tab.

5. Unfold the row.
It looks like this:
![image](https://user-images.githubusercontent.com/71872483/151631435-0e41219e-1027-498d-a573-dfcfe77d11ca.png)
Seems like the card did not update it's height.

6. Refresh the tab (swipe down).
Now the card looks OK:
![image](https://user-images.githubusercontent.com/71872483/151631845-0d26a68e-25cc-4e2d-ba7b-030ad7e808df.png)

The only way to reproduce the glitch is "select to another tab, refresh it, go back to the 1st tab".
