### ISSUE TITLE
fold-entity-row glitches on iOS if it contains another fold-entity-rows

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-fold-entity-row#199]
My Home Assistant version: 2021.12.6

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.12

What I am doing:
Expanding a fold-entity-row on iPad client.
This row contains another fold-entity-rows.

What I expected to happen:
1. Row is expanded.
2. All inserted rows are visible & work properly.

What happened instead:
iPad Air 2 (iOS 15.x):
the last row is clipped:
![изображение](https://user-images.githubusercontent.com/71872483/147602948-abf337c1-7d23-4cc1-8684-93e726daa52b.png)

Btw, what we see on iPhone 5S (iOS 12.x):
Basically I see this (the picture including other rows above the test card):
![изображение](https://user-images.githubusercontent.com/71872483/147603530-408eb65a-bb89-4dfa-9e83-f7b28c19a5b3.png)
(related to another issue - https://github.com/thomasloven/lovelace-fold-entity-row/issues/198), but if I managed to display it (after cleaning cache, reloading App) then I just cannot expand some rows (at least containing another fold-entity-rows, button-rows and other conventional rows supported in Entities card).

**Minimal** steps to reproduce:
```
type: entities
entities:
  - sun.sun
  - type: custom:fold-entity-row
    head:
      type: section
      label: section
    padding: 10
    open: false
    entities:
      - sun.sun
      - type: custom:fold-entity-row
        head:
          type: section
          label: section
        padding: 10
        open: false
        entities:
          - entity: sun.sun
          - entity: sun.sun
      - type: custom:fold-entity-row
        head:
          type: section
          label: section
        padding: 10
        open: false
        entities:
          - entity: sun.sun
          - entity: sun.sun
```

Error messages from the browser console:
no
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Do not see it in 12.0.4

**Comment by thomasloven** [comment]
Great! I forgot to ping this issue when I updated - sorry.

**Comment by ildar170975** [comment]
Thomas, unfortunately I see a glitch on iPhone 5s (iOS 12.5.5).

This is how it looks in iPad Air 2 (iOS 15.x)^
![image](https://user-images.githubusercontent.com/71872483/151625856-3fc67927-ab3e-427a-a0b4-29742d0622cb.png)

And how it looks on iPhone when folded:
![image](https://user-images.githubusercontent.com/71872483/151625983-9ae9141a-c106-4d4e-af5d-5d8b5c2b7de7.png)
Note - the next card is a `vertical-stack` with a `markdown` card.
When unfolded - there is a glitch:
![image](https://user-images.githubusercontent.com/71872483/151626254-ba8c4e4e-a498-4d87-ab51-c4e0f0a1dc9c.png)
I see this glitch ALWAYS.

**Comment by thomasloven** [comment]
Guess I'm dusting off the ipad air 1 again...

**Comment by ildar170975** [comment]
So, on iPad Air 2 - OK, on iPhone 5S - not OK...

**Comment by dapuzz** [comment]
Not sure this is fixed 🙃
![18A602AB-01CC-424E-ADE1-8158052FA140](https://user-images.githubusercontent.com/45406499/151628957-cfe26986-b4c9-44ee-ae57-b9a8acbefc37.jpeg)
iPhone XR iOS 13

thank you

**Comment by thomasloven** [comment]
Should be fixed now.

**Comment by ildar170975** [comment]
Now it is broken even for iPad Air 2 (iOS 15.x) and even for a case "fold-entity-row does NOT contain another fold-entity-row" (((
![image](https://user-images.githubusercontent.com/71872483/151683379-bf1481a1-2863-4df2-9d4b-7d2ec2b2ac37.png)
```
type: entities
entities:
  - entity: sun.sun
    secondary_info: last-changed
  - type: custom:fold-entity-row
    head:
      entity: sun.sun
      secondary_info: last-changed
    padding: 5
    no_animation: true
    open: true
    entities:
      - entity: sun.sun
        secondary_info: last-changed
      - entity: sun.sun
        secondary_info: last-changed
  - type: custom:fold-entity-row
    head:
      type: section
      label: Section
    padding: 5
    open: true
    group_config:
      secondary_info: last-changed
      icon: mdi:desk-lamp
    entities:
      - sun.sun
      - sun.sun
  - type: section
  - type: custom:fold-entity-row
    head:
      entity: input_boolean.test_boolean
    padding: 50
    open: false
    entities:
      - entity: sun.sun
      - entity: sun.sun
        secondary_info: last-changed
```
