### ISSUE TITLE
Hide Group Control

### ISSUE THREAD

**Issue by GatoPharaoh** [thomasloven/lovelace-fold-entity-row#2]
Love this card - exactly what I was looking for

_One issue I encountered:_

Is there some possibility to hide the control button for the whole group? (it is hidden outside of lovelace but lovelace itself seems to ignore `control:hidden` in customize.yaml)

thanks in advance

**Comment by steve28** [comment]
I have the opposite problem.  It won't show the group control at all.  I am trying to use the group `group.all_automations` so I can have a quick way of turning off all automations when I'm working on stuff.
```yaml
      - type: entities
        title: Automations
        entities:
          - entity: group.all_automations
            type: custom:folding-group-entity-row
```

And here's what I get:

![image](https://user-images.githubusercontent.com/5874433/46911456-560ebc00-cf11-11e8-8388-a7dc037a747e.png)
