### ISSUE TITLE
Custom element doesn't exist: hui-entities-entity-row

### ISSUE THREAD

**Issue by wbilger** [thomasloven/lovelace-fold-entity-row#20]
Before .84 and the last update to the card, the following worked, but now gives the error ' Custom element doesn't exist: hui-entities-entity-row'
The error is in the head, row still unfolds and entities within it work.

```yaml
- type: custom:fold-entity-row
  head:
    type: entities
    entity: light.family_room_light
    name: Fan Light
  items:
    - type: custom:slider-entity-row
      entity: light.family_room_light
      name: Fan Light
      full_row: true
    - type: custom:slider-entity-row
      entity: light.family_room_1
      name: Light 1
      toggle: true
    - type: custom:slider-entity-row
      entity: light.family_room_2
      name: Light 2
      toggle: true
```
