### ISSUE TITLE
Trying to nest auto-entities inside fold-entity-row displays border

### ISSUE THREAD

**Issue by nchieffo** [thomasloven/lovelace-fold-entity-row#200]
Hello
What I'd like to achieve is a card that will display lights in 'on' state, with a folded section to display lights in off state
I'm not sure what I'm trying to achieve is correct, because I'm using it inside auto-entities card instead of entities card.

```
type: custom:auto-entities
card:
  type: entities
  title: Lights
filter:
  include:
    - domain: light
      state: 'on'
    - type: custom:fold-entity-row
      head:
        type: section
        label: Off
      entities:
        - type: custom:auto-entities
          card:
            type: entities
          filter:
            include:
              - domain: light
                state: 'off'
```

The result is OK, but inside the foldable area I see the card border

![image](https://user-images.githubusercontent.com/632266/147848030-26db92a9-f25f-45b8-8e87-56d87e159674.png)

Do you think it's possible to remove the border?

Thanks
