### ISSUE TITLE
Issues with toggling lights with the top card toggle

### ISSUE THREAD

**Issue by rhoriguchi** [thomasloven/lovelace-fold-entity-row#204]
My Home Assistant version: 2021.12.10

What I am doing:
Toggle the top card toggle.

![image](https://user-images.githubusercontent.com/6047658/151444236-a3602025-f306-48b7-8600-d9d80a444854.png)

What I expected to happen:
The top toggle should toggle all lights on also the group and its sub lights.

What happened instead:
It only toggles the `Living room` light but not the `Entrance` light group and its sub lights (`Hallway`, `Window`).

---

**Minimal** steps to reproduce:

configuration.yaml
```yaml
yeelight:
  devices:
    yeelink-light-mono5_mibt1D55.iot:
      model: mono5
      name: Entrance window
    yeelink-light-mono5_mibt9166.iot:
      model: mono5
      name: Entrance hallway

light:
- entities:
  - light.entrance_hallway
  - light.entrance_window
  name: Entrance
  platform: group

# Living room is a  template switch witch gets used as a light with a light `turn_on` and `turn_off` behavior, but this bug happens with any light with a single light and a group.
```

ui-lovelace.yaml
```yaml
resources:
- type: module
  url: /local/hs-lovelace-module-fold-entity-row.js?v=2.0.13
title: Home
views:
- cards:
  - entities:
    - light.bedroom
    - entities:
      - entity: light.entrance_hallway
        name: Hallway
      - entity: light.entrance_window
        name: Window
      head: light.entrance
      type: custom:fold-entity-row
    show_header_toggle: true
    title: Lights
    type: entities
```

Error messages from the browser console:
None

---

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
That's a limitation in Home Assistant. Nothing I can do, unfortunately.

**Comment by carlos-sarmiento** [comment]
@thomasloven, could you elaborate on the reason this limitation exists on Home Assistant? I'm also struggling with this pain point and would like to either open an issue with them or work on a PR to fix it

**Comment by ildar170975** [comment]
Try to create this simple test:
```
type: entities
title: test
entities:
  - entity: light.xxxxxxxxxx
  - type: custom:fold-entity-row
    head: group.lights_yyyyyyyyyyy
    open: true
    entities:
      - light.yyyyyyyyyy_1
      - light.yyyyyyyyyy_1
      - ....
      - light.yyyyyyyyyy_5
```
This is how it looks in UI editor:
![image](https://user-images.githubusercontent.com/71872483/174676900-92efe2da-7da2-407d-9d73-af8b0dfdd47e.png)

Note that the "Show header toggle" = ON **by default** - but the header toggle is NOT added:
![image](https://user-images.githubusercontent.com/71872483/174677518-6faf5f3f-5a16-44f8-bc7e-38cb9cdd5591.png)

It happens because HA adds the toggle only **if more the one "toggleable row" is present** (`input_boolean`, `switch`).
Here HA thinks that only ONE "toggleable row" is present - HA seems to not consider this custom row as "toggleable".

Then add some `input_boolean` row:
```
      - entity: input_boolean.test_boolean
```
And see what happens - the header toggle is added:
![image](https://user-images.githubusercontent.com/71872483/174677448-aaacb003-c1ec-498c-b122-54a4bc24a41d.png)

Conclusion - the header toggle works with conventional rows only.
