### ISSUE TITLE
iPhone: Entities card with one `fold-entity-row` does not change it's height when the row is unfolded

### ISSUE THREAD

**Issue by ildar170975** [thomasloven/lovelace-fold-entity-row#206]
My Home Assistant version: 2021.12.10

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.14

What I am doing:
Found a new issue on iPhone 5S (iOS 12.5.5).
Unfolding a `fold-entity-row` inside an Entities card.

What I expected to happen:
Everything works fine.

What happened instead:
The Entities card does not change it's height when the row is unfolded.

**Minimal** steps to reproduce:
1. Create a new tab.
2. Add this card:
```
type: entities
entities:
  - type: custom:fold-entity-row
    open: false
    padding: 0
    head:
      entity: input_boolean.test_boolean
    entities:
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
```
3. It looks like this:
![image](https://user-images.githubusercontent.com/71872483/151631188-e213bcf9-85ef-4416-b6df-1f3dff4d60df.png)

4. To reproduce the glitch - go to another tab and refresh it (swipe down).
Go back to the 1st tab.

5. Unfold the row.
It looks like this:
![image](https://user-images.githubusercontent.com/71872483/151631435-0e41219e-1027-498d-a573-dfcfe77d11ca.png)
Seems like the card did not update it's height.

6. Refresh the tab (swipe down).
Now the card looks OK:
![image](https://user-images.githubusercontent.com/71872483/151631845-0d26a68e-25cc-4e2d-ba7b-030ad7e808df.png)

The only way to reproduce the glitch is "select to another tab, refresh it, go back to the 1st tab".

Error messages from the browser console:
None
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
