### ISSUE TITLE
2.1.0: folds auto open when scroll mod is used

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#207]
My Home Assistant version: 2022.3.0.dev20220130

Fold-entity-row version (FROM BROWSER CONSOLE): 2.1.0

What I am doing:

adding a card_mod to have the entities in a fold use a scroll bar, and this worked beautifully up to 20.0.14

What I expected to happen:

folds remain closed until click

What happened instead:

folds auto open
we can click the fold, and see the icon change, the entities list itself though is not changing. Also the scroll isnt available anymore, and the list is stuck at max-height.

<img width="485" alt="Schermafbeelding 2022-01-31 om 11 25 59" src="https://user-images.githubusercontent.com/33354141/151777382-7a6fc9e0-1dd3-4fd3-96b6-0cab3dd098f4.png">
<img width="500" alt="Schermafbeelding 2022-01-31 om 11 26 12" src="https://user-images.githubusercontent.com/33354141/151777391-4467fb17-8758-483c-9ef8-1c6fa37392e9.png">

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
  - type: entities
    entities:
      - type: custom:fold-entity-row
        card_mod:
          style: |
            div#items {
              overflow-y: scroll;
              max-height: 400px !important;
            }
        head:
          type: section
          label: Inside
# End of code
```

Error messages from the browser console:
No errors
---

bringing back 20012 results in:

![Jan-31-2022 11-31-42](https://user-images.githubusercontent.com/33354141/151778181-5e942a6f-6a3a-4135-9031-aeebe95a2e03.gif)
<img width="503" alt="Schermafbeelding 2022-01-31 om 11 30 35" src="https://user-images.githubusercontent.com/33354141/151778195-0fdd4b98-e7da-4488-b3d0-8b2054dfdec6.png">

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
