### ISSUE TITLE
'unavailable' overflows card in fold

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#208]
My Home Assistant version: 2022.3.0.dev20220201

Fold-entity-row version (FROM BROWSER CONSOLE): 2.1.0

What I am doing:

showing several sensors off a sonoff switch

What I expected to happen:

have the 'unavailable' of the sensors in the fold remain within the card
What happened instead:

<img width="572" alt="Schermafbeelding 2022-02-01 om 12 02 28" src="https://user-images.githubusercontent.com/33354141/151957388-4c5e4373-2d75-49da-bba3-9b708bfd882f.png">

this is a switch, which only populates these sensors in 'on' state:

<img width="500" alt="Schermafbeelding 2022-02-01 om 11 52 22" src="https://user-images.githubusercontent.com/33354141/151957651-a241423e-5f66-4676-8c11-ee8d524affad.png">

which makes another fine example for the FR https://github.com/thomasloven/lovelace-fold-entity-row/issues/193 , if none of these are available, dont show the fold.

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
  - type: entities
    title: Symfonisk dining
    card_mod: *header
    show_header_toggle: false
    entities:
      - switch.symfonisk_dining
      - media_player.symfonisk

      - type: custom:fold-entity-row
        head:
          type: section
          label: Settings
          card_mod:
            style: |
              .label {
                margin-left: 0px;
              }
        padding: 0
        no_animation: true
        entities:
          - switch.sonos_symfonisk_crossfade
          - switch.sonos_symfonisk_status_light
          - switch.sonos_symfonisk_touch_controls
          - number.symfonisk_bass
          - number.symfonisk_treble
# End of code
```

Error messages from the browser console:
nothing relevant
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
Things that happen in fold-entity-row and also without fold-entity-row are not caused by fold-entity-row.

![image](https://user-images.githubusercontent.com/1299821/151964057-ef013a96-a490-420a-9db8-f81ac7fb360b.png)

**Comment by thomasloven** [comment]
Also, this is rather an excellent counterexample.
```yaml
- type: conditional
  conditions:
    - entity: switch.symfonisk_dining
      state: "on"
      row:
        type: custom:fold-entity-row
        ...
```

**Comment by Mariusthvdb** [comment]
thanks Thomas,
I've grown accustomed to prevent the conditional as much as possible, because it always  leaves a small gap. In this case that isnt really harming the card, so yes, a great solution

as door the overflow: I hadn't noticed it in any other card yet. and have comparable card showing correctly:

<img width="518" alt="Schermafbeelding 2022-02-01 om 13 17 13" src="https://user-images.githubusercontent.com/33354141/151966978-dd227a59-9c08-4fdb-8caa-294f24d1a09a.png">

this being a number issue then? in which case I ll drop a line in the frontend repo.

please close? I can seem to find the button for that below

**Comment by Mariusthvdb** [comment]
one more thing...

I made a mistake and did:

```
    entities:
      - switch.symfonisk_dining
      - media_player.symfonisk

      - type: conditional
        conditions:
          - entity: switch.symfonisk_dining
            state: 'on'
        row:
          - type: custom:fold-entity-row
            head:
              type: section
              label: Settings
```

instead of leaving the `-` out in front of `type_custom:fold-entity-row` , as you showed in your suggestion above.

this lead to an error which source I cant understand:

<img width="530" alt="Schermafbeelding 2022-02-01 om 13 33 03" src="https://user-images.githubusercontent.com/33354141/151969311-e9096d79-7235-4aa7-a5a5-2d869a1f1f27.png">
 mentioning ha-logbook and auto-entities.


At first I thought it might have to do with several anchors (which could be declared above in an auto-entities ,) so I created a standalone card config. Still that error remains.

Ive fixed the card, working beautifully, but the error is mesmerizing....
