### ISSUE TITLE
2.1.0 results in a slower Frontend than 20.0.12

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#209]
My Home Assistant version: dev20220201

Fold-entity-row version (FROM BROWSER CONSOLE): 2.1.0 vs 20.0.12

What I am doing:

comparing the 2 versions

What I expected to happen:

2.1.0 be more snappy
What happened instead:
20.0.12 is more snappy

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
entities:

  - type: custom:fold-entity-row
    head:
      type: section
      label: Family home
      card_mod: &label
        style: |
          .label {
            margin-left: 0px;
          }
    <<: &config
      padding: 0
      no_animation: true
    entities:
# End of code
```

Having compared the 2 versions for the last day extensively and having edited all of my many folds with the settings above, I must confess the new resource makes the whole Frontend much less snappy. Views take a longer time to load, before they have all tabs and cards in place. 

Once the view is loaded completely, the folds behave ok.

I can't be scientific, but intend to be as correct as can be (...) , but the difference is quite big. I've left the new configs in place (the 20012 will simply ignore that) and put 20012 back, reloaded the resources and voila, a much snappier interface.

Not sure what the reason is. Is it the amount of cards I have? dont think so, because it's the same in both situations. It's not the amount of mods, nor the amount of includes (which I rely on heavily), because the whole config remains identical.

I can see no other conclusion than the new 2.1.0 resource doing something very different, and that is expensive. Is it the transition check (no_animation)?

Please if you have any hint as to what could be causing this let me know. on my part, as Ive pointed out elsewhere, did comment out the #measure section:

```
     /* #measure {
        overflow: clip visible;
      }
      #measure > * {
        margin: 8px 0;
        overflow: clip visible;
      }
      #measure > *:last-child {
        margin-bottom: 0;
        overflow: clip visible;
      }

      #measure > div * {
        overflow: clip visible;
      }
      #head > *:first-child {
        overflow: clip visible;
      } */
```

and havent done so in the 2.1.0 version because I believed the t to be critical for the last-child in the fold issue, which 2.1.0 has fixed?

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
