### ISSUE TITLE
Group opened but collapsed

### ISSUE THREAD

**Issue by mmkrysiak** [thomasloven/lovelace-fold-entity-row#210]
My Home Assistant version: 2022.2.2

Fold-entity-row version 2.1.0

What I am doing:
Open section, change card and back

What I expected to happen:
Opened section/group of entities should be open
or
if section shows collapsed arrow on the right hand side should point down

What happened instead:
arrow pointed up (suggested that section is open) but show section collapsed.
To open it's necessary to click arrow twice
![image](https://user-images.githubusercontent.com/71908475/152683136-da1fb376-a83b-4cfd-96cb-88466356e322.png)

**Minimal** steps to reproduce:

```yaml
type: entities
entities:
  - type: custom:fold-entity-row
    head: light.posesja
    entities:
      - entity: light.wejscie
      - entity: light.wjazd
      - entity: light.palenisko
  - type: divider
  - type: custom:fold-entity-row
    head: light.halogeny
    entities:
      - entity: light.halogen_front
      - entity: light.halogen_garaze
      - entity: light.halogen_ogrod
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [] Have made sure I am using the latest version of the plugin.
- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
Tried to simulate the case.
Do not have a `light` group, used my own `group.batteries` group:
```
type: entities
entities:
  - type: custom:fold-entity-row
    head: group.batteries
    entities:
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
```
![изображение](https://user-images.githubusercontent.com/71872483/152694820-b51ccbca-7573-4569-b1f6-6ed64d982280.png)
Works smooth w/o issues.

**Comment by thomasloven** [comment]
What does "change card" mean?

**Comment by mmkrysiak** [comment]
I mean dashboard page or another dashboard.

**Comment by ildar170975** [comment]
I "change" means "switch to another tab" - then I have to confirm the issue.
It happens not only with a group entity.
```
type: entities
entities:
  - type: custom:fold-entity-row
    head: sun.sun
    entities:
      - entity: sun.sun
      - entity: sun.sun
      - entity: sun.sun
```
How to reproduce:
1. Unfold.
2. Switch to another tab.
3. Return to the 1st tab.
4. The card is folded but the chevron button says "unfolded".
5. Fold - then after a small animation the card is folded and the chevron says "folded"
