### ISSUE TITLE
Fr?/Bug.. Changing icon size back to 24px moves divider out of the right side card

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#211]
My Home Assistant version: 2022.3.0.dev20220208

Fold-entity-row version (FROM BROWSER CONSOLE): 2.2.0

What I am doing:
editing the resource (so I am causing a bug...) hence this might also be a FR to bring back 24 px icon size....

What I expected to happen:
divider remains inside card
What happened instead:
overflow:

<img width="115" alt="Schermafbeelding 2022-02-08 om 23 26 46" src="https://user-images.githubusercontent.com/33354141/153086630-0d515a8c-8de4-4d36-96a9-d31ca815b831.png">

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
      #head {
        display: flex;
        align-items: center;
        --toggle-icon-width: 32px;
      }

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [] Have made sure I am using the latest version of the plugin.
- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
