### ISSUE TITLE
Cant remove empty header

### ISSUE THREAD

**Issue by KitHubek** [thomasloven/lovelace-fold-entity-row#212]
My Home Assistant version: 2022.2.6

Fold-entity-row version (FROM BROWSER CONSOLE): 2.2.0

What I am doing: try to add card

What I expected to happen: see card without empty header

What happened instead: empty header appear like screenshot below:

![foldtest](https://user-images.githubusercontent.com/91805313/153744165-014a1b99-9baf-40dd-a189-b864d0beeec0.jpg)

**Minimal** steps to reproduce: just try add new card with fold entity row just like for example this:

```yaml
# The least amount of code possible to reproduce my error
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      type: section
      label: test
    open: false
    entities:
      - switch.xiaomi_plug_hades
show_header_toggle: false
state_color: true
# End of code
```

Error messages from the browser console: no error, just card looks not nice

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
