### ISSUE TITLE
no header_toggle on entities card with only folds (containing only switches)

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#213]
My Home Assistant version: 2022.3.0.dev20220214

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.12 (tested 2.2.0 too, no luck)

What I am doing:

showing several fold-entity-row cards in an entities card, each fold containing  only core switches

What I expected to happen:

have the entities card show a toggle in the header

What happened instead:

no toggle
would this be relates to the older issue. https://github.com/thomasloven/lovelace-fold-entity-row/issues/22 ? 

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
type: entities
title: Hue motion sensor switches
state_color: true
show_header_toggle: true # <--- should be default, but set it to be sure..
entities:

  - type: custom:fold-entity-row
    head:
      type: section
      label: Rooms
    padding: 0
    entities:
      - entity: switch.dining_table_sensor_motion
        name: Dining table
        secondary_info: last-changed
      - entity: switch.auditorium_sensor_motion
        name: Auditorium
        secondary_info: last-changed
  - type: custom:fold-entity-row
    head:
      type: section
      label: Rooms 2
    padding: 0
    entities:
# End of code
```

Error messages from the browser console:

No error
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
