### ISSUE TITLE
also show divider when using head: group and add last_changed to head if configured

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#214]
using:
```
type: entities
title: Hue motion sensor switches
state_color: true
show_header_toggle: true
entities:
  - type: custom:fold-entity-row
    head: group.philips_room_motion_sensor_switches
    group_config:
      secondary_info: last-changed
#      type: section
#      label: Rooms
    padding: 0
#    entities:
#      - entity: switch.dining_table_sensor_motion
#        name: Dining table
#        secondary_info: last-changed
#      - entity: switch.auditorium_sensor_motion
#        name: Auditorium
#        secondary_info: last-changed


  - type: custom:fold-entity-row
    head: group.philips_always_on_motion_sensor_switches
    group_config:
      secondary_info: last-changed
    padding: 0

  - type: custom:fold-entity-row
    head: group.philips_buiten_motion_sensor_switches
    group_config:
      secondary_info: last-changed
    padding: 0
```

has 2 details Id like to FR. 
- there's no longer a divider showing, as there is when using a type: section. I am aware `section` causes the divider to show, and we can add an extra `type: divider` but that still doesnt result in the same frontend effect. please consider adding a section divider optionally?
- setting the group_config to use last_changed works beautifully, however doesnt touch the header: please consider adding last_changed to the header too?

with extra type: divider between the top 2 folds

<img width="502" alt="Schermafbeelding 2022-02-17 om 12 52 06" src="https://user-images.githubusercontent.com/33354141/154476048-1ba9f797-f4e9-45bb-8948-d0ff7362d34d.png">

**Comment by thomasloven** [comment]
AS you say, the divider line isn't fold-entity-row, and I don't feel it should be in the scope of it either.

```yaml
head:
  entity: group.philips...
  secondary_info: last-changed
```
