### ISSUE TITLE
card-mod wont move label any more on HA 2022.4.x

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#216]
My Home Assistant version: 2022.4.0.dev20220225 frontend 20220223.0

Fold-entity-row version (FROM BROWSER CONSOLE): 2.2.0

What I am doing:

card-mod on the label to move it left

posting this here ( and not in card-mod), since you specifically asked for f-e-r feedback in the current #beta channel on Discord, and I noticed this happening in my dev/nightly instance.

What I expected to happen:

have the label positioned horizontally like the section header, see image below,

What happened instead:

new HA version seems to interfere, and doesnt change the position any longer 

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
      card_mod: &label
        style: |
          .label {
            margin-left: 0px;
          }
# End of code
```

Error messages from the browser console:

no error so it seems

though this isnt about f-e-r not working And missing an entities: line.... this is a bigger section of the yaml:

```
type: entities
entities:

  - 
  - type: custom:fold-entity-row
    <<: *scroll
    head:
      type: section
      label: Active threshold
      card_mod: *label
    padding: 0
    entities:
      - type: custom:auto-entities
        card:
          type: entities
          card_mod: *mod
        filter:
          include:
            - group: group.active_devices
              options:
                secondary_info: last-changed
        sort:
          method: state
          reverse: true

  - type: section
    label: Related auto groups
    card_mod: *label

  - type: custom:fold-entity-row
    <<: *scroll
    head:
      type: section
      label: Sensors actueel
      card_mod: *label
    padding: 0
    entities:
      - type: custom:auto-entities
        card:
          type: entities
          card_mod: *mod
        filter:
          include:
            - entity_id: 'sensor.*_actueel'
        sort:
          method: state
          numeric: true
          reverse: true
```

and an image:

<img width="512" alt="Schermafbeelding 2022-02-25 om 10 52 34" src="https://user-images.githubusercontent.com/33354141/155694947-ca72a5a6-9ba2-4629-b73a-fc52a10fc6c3.png">

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
