### ISSUE TITLE
multiple-entity-row items are cut off at the bottom of fold-entity-row

### ISSUE THREAD

**Issue by maxl67** [thomasloven/lovelace-fold-entity-row#219]
My Home Assistant version: 2022.03.2

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.12
multiple-entity-row: 4.4.1
Both lovelace add-ones are installed via HACS. I always use the newest version.

What I am doing: 
I am often using multiple-entity-row items within fold-entity-row items. 
I am not sure which of this 2 components causes the described problems. I suspect more Fold-entity-row to be the cause, so I post this issue here first. If not, I will post it in the multiple-entity-row repo.

What I expected to happen:
All information within the multiple-entity-row should be displayed completely.
This worked in the past but with some version in the past (maybe summer/fall 2021) the behavior changed. Unfortunately I cannot remember when exactly.

What happened instead:
If the last row within a fold-entity-row item is of type multiple-entity-row and displays 2 lines of information, then part at the bottom is not displayed. This issue does not appear, if the multiple-entity-row is not used with fold-entity-row.

![example](https://user-images.githubusercontent.com/55485759/157214104-03b2e753-9bd7-420a-90f8-b0a2f90ed3ee.jpg)

**Minimal** steps to reproduce:

```yaml
type: entities
title: Hera (DS916+)
show_header_toggle: false
entities:
  - type: custom:fold-entity-row
    head:
      type: section
      label: System
    entities:
      - entity: sensor.hera_cpu_load_total
        type: custom:multiple-entity-row
        name: CPU Usage
        secondary_info: last-changed
        entities:
          - entity: sensor.hera_cpu_load_15_min
            name: proc load 15'
      - entity: sensor.hera_memory_usage_real
        name: Memory Usage
        secondary_info: last-changed
        type: custom:multiple-entity-row
        entities:
          - entity: sensor.memory_free
            name: free
  - type: custom:fold-entity-row
    head:
      type: section
      label: Volume 1
    entities:
      - entity: sensor.hera_volume_1_status
        name: Status Volume 1
        icon: mdi:database-check
        type: custom:multiple-entity-row
        secondary_info: last-changed
        state_header: state
        entities:
          - entity: sensor.hera_volume_1_max_disk_temp
            name: max temp
      - type: custom:fold-entity-row
        head:
          type: section
          label: Disks
        open: true
        padding: 0 px
        entities:
          - entity: sensor.hera_drive_1_status
            type: custom:multiple-entity-row
            icon: mdi:harddisk
            name: Disk1 (sda)
            secondary_info: last-changed
            state_header: state
            entities:
              - entity: sensor.hera_drive_1_temperature
                name: temp
          - entity: sensor.hera_drive_2_status
            type: custom:multiple-entity-row
            icon: mdi:harddisk
            name: Disk2 (sdb)
            secondary_info: last-changed
            state_header: state
            entities:
              - entity: sensor.hera_drive_2_temperature
                name: temp
  - type: section
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
The latest fold-entity-row version is 2.2.0. I apologize for the version number confusion.

**Comment by maxl67** [comment]
Thanks for your quick answer and the excellent work you have done. 
I updated to latest version 2.2.0 but problem still persists.

**Comment by ildar170975** [comment]
Do not confirm any cutoff:
```
type: entities
title: Hera (DS916+)
show_header_toggle: false
entities:
  - type: custom:fold-entity-row
    head:
      type: section
      label: System
    entities:
      - entity: sensor.processor_use
        type: custom:multiple-entity-row
        name: CPU Usage
        secondary_info: last-changed
        entities:
          - entity: sensor.processor_use
            name: proc load 15'
      - entity: sensor.processor_use
        name: Memory Usage
        secondary_info: last-changed
        type: custom:multiple-entity-row
        entities:
          - entity: sensor.processor_use
            name: free
  - type: custom:fold-entity-row
    head:
      type: section
      label: Volume 1
    entities:
      - entity: sensor.processor_use
        name: Status Volume 1
        icon: mdi:database-check
        type: custom:multiple-entity-row
        secondary_info: last-changed
        state_header: state
        entities:
          - entity: sensor.processor_use
            name: max temp
      - type: custom:fold-entity-row
        head:
          type: section
          label: Disks
        open: true
        padding: 0 px
        entities:
          - entity: sensor.processor_use
            type: custom:multiple-entity-row
            icon: mdi:harddisk
            name: Disk1 (sda)
            secondary_info: last-changed
            state_header: state
            entities:
              - entity: sensor.processor_use
                name: temp
          - entity: sensor.processor_use
            type: custom:multiple-entity-row
            icon: mdi:harddisk
            name: Disk2 (sdb)
            secondary_info: last-changed
            state_header: state
            entities:
              - entity: sensor.processor_use
                name: temp
  - type: section
```
![image](https://user-images.githubusercontent.com/71872483/157761518-abf39a5d-6bef-4a72-bcbf-1362e2dff7af.png)

![image](https://user-images.githubusercontent.com/71872483/157761641-5307408c-20f6-4fb1-9c43-7c4796eadb4a.png)
