### ISSUE TITLE
groups in groups makes header toggle behave incorrectly

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#22]
HI,

Using groups in groups with the fold-entity-row, makes the header behave incorrectly (it does nothing...)

as you can see below, the groups themselves work, even the group Kantoor, which behaves of 2 groups shows the correct header. The card header stays Off:

![schermafbeelding 2018-12-18 om 10 06 06](https://user-images.githubusercontent.com/33354141/50143419-d0124700-02ac-11e9-8217-bcaa25c1ca87.jpg)

using this code:

```
  - type: entities
    title: Folding entities Tradfri
    group_config:
      secondary_info: last-changed
    entities:
      - type: custom:fold-entity-row
        head: group.bureau_lights
      - type: custom:fold-entity-row
        head: group.office_lights
      - type: custom:fold-entity-row
        head: group.guest_room_lights
      - type: custom:fold-entity-row
        head: group.hallway_lights
      - type: custom:fold-entity-row
        head: group.library_lights
      - type: custom:fold-entity-row
        head: group.hobby_corner_lights
      - type: custom:fold-entity-row
        head: group.gamers_den_lights
      - type: custom:fold-entity-row
        head: group.kantoor_lights
      - type: custom:fold-entity-row
        head: group.gym_lights
```

I have now taken out the header_toggle as to not confuse the users, but it should behave correctly in the first place of course. Appreciate if you could have a look!
thx
