### ISSUE TITLE
hide the exband-button

### ISSUE THREAD

**Issue by YvesZH** [thomasloven/lovelace-fold-entity-row#225]
I have  new idea (workarround) about the placement of the "exband-button"(future request #119 
1. the future request "expand&close by a other entity" is being expected (future request #173 )
2. the user can make a input_bolean
3. the user can set an icon with the [paper-buttons-row](https://github.com/jcwillox/lovelace-paper-buttons-row) on the left on the toggles-switch (or everywhere he like in the lovelace panel)
4. the only thing that is additionally expected: the option to hide the exband-button

**Config example:**
```
type: entities
entities:
  - type: custom:fold-entity-row
     open: entity
       condition_entity: input_boolean.exband
       condition_state: "on"
       hide_exband_button: true
    entities:
      - light.bed_light`
```
