### ISSUE TITLE
Support for conditional card within fold entity row card

### ISSUE THREAD

**Issue by moostmartijn** [thomasloven/lovelace-fold-entity-row#229]
I'm not sure if this would be even possible, but I would like to accomplish this card:

```
              - type: custom:fold-entity-row
                head:
                  type: custom:button-card # SECTION KEUKEN
                  name: Keuken
                  tap_action:
                    action: none
                  styles:
                    card:
                      - margin-bottom: 0px
                      - padding-bottom: 0px
                      - padding-top: 0px
                      - box-shadow: none
                    name:
                      - justify-self: start
                      - padding-left: 8px
                      - font-size: 16px
                      - font-weight: 500
                      - padding-bottom: 0px
                      - padding-top: 0px
                      - bottom: 0px
                entities:
                  - type: custom:multiple-entity-row
                    entity: light.keuken
                    name: " "
                    icon: " "
                    show_state: false
                    entities:
                      - entity: light.keuken_spots
                        name: Keuken spots
                        toggle: true
                        icon: hue:ceiling-fugato-three
                        tap_action:
                          action: toggle 
                      - entity: light.ecosysteem
                        name: Ecosysteem
                        toggle: true
                        icon: mdi:sprout-outline
                        tap_action:
                          action: toggle                                  
                      - type: conditional
                        conditions:
                          - entity: light.keuken
                            state: "off"
                        card:
                          entity: light.keuken
                          name: Keuken
                          toggle: true    
                          icon: hue:bulb-group-ceiling-flush-circular       
                          tap_action:
                            action: toggle
```
It's all about the conditional card at the end which is not supported at the moment.

This is the card I have right now, and I would like to only show the icon whenever the light is off. 

<img width="476" alt="Schermafbeelding 2022-07-25 om 22 14 15" src="https://user-images.githubusercontent.com/31592734/180866484-c121a346-cdb6-4fd3-a3b3-2add942139d6.png">

Thanks in advance.
