### ISSUE TITLE
Can't include head: options when using inside a auto-entities group filter

### ISSUE THREAD

**Issue by ajma** [thomasloven/lovelace-fold-entity-row#230]
My Home Assistant version: 2021.09.7

Fold-entity-row version (FROM BROWSER CONSOLE): 20.0.12

What I am doing: Trying to set ```head``` inside a ```auto-entities``` group filter

What I expected to happen: entity shows up with secondary-info in the head

What happened instead: secondary-info isn't showing up. the entities inside the group are showing up with the right state but without the secondary info

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error

type: custom:auto-entities
card:
  type: entities
filter:
  include:
    - group: light.downstairs
      or:
        - state: 'on'
      options:
        type: custom:fold-entity-row
        head:
          entity: light.downstairs
          secondary_info: last-changed
        group_config:
          secondary_info: last-changed


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
The code is wrong.
[A proper code is clearly described in the docs.](https://github.com/thomasloven/lovelace-fold-entity-row#advanced)
```
type: entities
entities:
  - type: custom:auto-entities
    filter:
      include:
        - group: # add group sensor
          # add whatever you want
    card:
      type: custom:fold-entity-row
      head:
        entity: # add your entity
        secondary_info: last-changed
      group_config:
        secondary_info: last-changed
```

**Comment by ajma** [comment]
But doesn't that make everything in the auto-entities list a fold-entity-row? I only want that single group to be a fold-entity-row. My code almost works, it does everything except show secondary-info in the head

**Comment by ildar170975** [comment]
> My code almost works, it does everything except show secondary-info in the head

It cannot work.
Check your code:
```
      options:
        type: custom:fold-entity-row
        head:
          entity: light.downstairs
```
which means - each row in the Entities card is `fold-entity-row` with some `head` and undefined folded `entities`.

You may do this:
```
type: custom:auto-entities
filter:
  include:
    - group: group.demo_lights
card:
  type: entities
```
which creates just a list of entities, w/o `fold-entity-row`.



> I only want that single group to be a fold-entity-row

And what?
![image](https://user-images.githubusercontent.com/71872483/192688194-b3160041-2e97-49af-86e2-3a818508f2a1.png)

**Comment by ajma** [comment]
Here's what I have:
![image](https://user-images.githubusercontent.com/136692/192697755-c9663ae5-9565-4f9e-872b-87e48f3b01b6.png)

groups.lock is just there to show that I'm using auto-entities to expand other groups into normal entities
but light.downstairs is expanded into the three rooms which are each fold-entity-row where the children have the secondary-info but I can't figure out the yaml to make the head also show secondary-info

**Comment by ajma** [comment]
The last example in the readmd has this:
```
type: custom:auto-entities
card:
  type: entities
  title: All groups
filter:
  include:
    - domain: group
      options:
        type: custom:fold-entity-row
```
I'm basically trying to use this but also set the `secondary-info` in the `head` but it looks like head is getting completely dropped.
Even if I do
```
head:
  type: section
  label: test
```
it doesn't keep label
