### ISSUE TITLE
`open` attribute can evaluate a template function

### ISSUE THREAD

**Issue by rhoriguchi** [thomasloven/lovelace-fold-entity-row#232]
A cool feature would be if you could add a function to `open` attribute instead of just a boolean since in some cases you don't want it open when you don't have a specific value.

My use case is when the parent entity value is `unknown` I don't want the toggle to be open since I don't have any data in the sub entities.

```yaml
type: custom:fold-entity-row

head:
  entity: sensor.ipv4_address_wlan0
  name: wlan0
  icon: mdi:web

open: '{{ not is_state(''sensor.ipv4_address_wlan0'', ''unknown'') }}'

entities:
- entity: sensor.network_throughput_in_wlan0
  name: Down
  icon: mdi:download
- entity: sensor.network_throughput_out_wlan0
  name: Up
  icon: mdi:upload
```
