### ISSUE TITLE
Allow customized Names

### ISSUE THREAD

**Issue by ChristophCaina** [thomasloven/lovelace-fold-entity-row#233]
Hi, I would really appreciate the possibility to add a custom name / text to the entity within your entity row.

For example:
```
type: entities
entities:
  - type: custom:fold-entity-row
    head: switch.waschmaschiene_outlet
    text: Waschmaschiene
    entities:
      - sensor.waschmaschiene_energy
        text: Energy
title: Waschmaschiene
```

or
```
type: entities
entities:
  - type: custom:fold-entity-row
    head: switch.waschmaschiene_outlet
    name: Waschmaschiene
    entities:
      - sensor.waschmaschiene_energy
        name: Energy
title: Waschmaschiene
```

Right now, this is not possible - and the card will always use the "friendly_name" of the entity...
In my case, I "merge" all entities from one device into a card - and therefore, I don't need the friendly_name at this place - but I can't rename the entity itself, because I need the friendly name on other areas, such as the energy dashboard (where I need the full name to identify the entity)

In this example, I am using 6 Meross-Smartplugs.
Each plug provides a list of entities - all are grouped together (so I have 6 different cards, each card has an entitiy for DEVICE-energy)
Renaming the entity to "energy" will cause 6 times an entity "energy" in my energy dashboard.

I hope, this kind of request does make sense?
