### ISSUE TITLE
Icons not displaying anymore since HA version 2023.2.x

### ISSUE THREAD

**Issue by bdormael** [thomasloven/lovelace-fold-entity-row#236]
I have noticed that after upgrading to HA 2023.2.x icons are not being displayed or formatted as before.

It’s the same issue as mentioned in custom:template-entity-row : https://github.com/thomasloven/lovelace-template-entity-row/issues/100

```yaml

- type: custom:fold-entity-row
        head:
          type: custom:template-entity-row
          icon: mdi:thermometer
          name: Temperaturen
          state: >-
            Buiten {{ state_attr("weather.forecast_thuis",
            "temperature")|round(1)}} °
        entities:
          - type: custom:template-entity-row
            icon: mdi:thermometer
            name: Beneden
            state: >-
              {{ state_attr("climate.beneden","current_temperature")|round(1)}}
              °
            tap_action:
              action: none
        

```

![Schermafbeelding 2023-02-04 om 08 05 24](https://user-images.githubusercontent.com/12784886/216754101-409561fa-3476-4482-bd74-4ba86e87e1e9.png)
