### ISSUE TITLE
group head toggle does not respect (old style) all: true config option

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#239]
My Home Assistant version: 2023.6.2

Fold-entity-row version 2.2.0

What I am doing:

```
  - type: custom:fold-entity-row
    head:
      type: section
      label: More-info (dialog) settings
      card_mod: *label
    <<: *config
    entities:
      - type: custom:fold-entity-row
        head: group.kiosk_mode_hide_dialog_header
#       - input_boolean.hide_dialog_header_history
#       - input_boolean.hide_dialog_header_settings
#       - input_boolean.hide_dialog_header_overflow
```
What I expected to happen:
have the group toggle repeat the all: true. 

What happened instead:

It behaves like the header toggle, which flips to on if a single entity in the group is on
**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
- type: custom:fold-entity-row
    head:
      type: section
      label: More-info (dialog) settings
    entities:
      - type: custom:fold-entity-row
        head: group.kiosk_mode_hide_dialog_header
# End of code
```

so we have to list these entities individually, and add a group type

```
    entities:
      - group.kiosk_mode_hide_dialog_header
      - type: divider
      - input_boolean.hide_dialog_header_history
      - input_boolean.hide_dialog_header_settings
      - input_boolean.hide_dialog_header_overflow
```

old style group yaml:
```
group:
  kiosk_mode_hide_dialog_header:
    name: Kiosk mode hide dialog header
    entities:
      - input_boolean.hide_dialog_header_history
      - input_boolean.hide_dialog_header_settings
      - input_boolean.hide_dialog_header_overflow
    all: true
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
