### ISSUE TITLE
Not working with entity-filter

### ISSUE THREAD

**Issue by wiuwiu** [thomasloven/lovelace-fold-entity-row#24]
Are you using: [https://www.home-assistant.io/lovelace/entity-filter/](url)
Because when I use:
```
type: entities
title: Entity Filter Fold
entities:
  - type: entity-filter
    entities:
      - light.bed_light
      - light.ceiling_lights
      - light.kitchen_lights
    state_filter:
      - "on"
    card:
      type: custom:fold-entity-row
      head:
        type: section
        label: Lit lamps
```
Nothing shows up. But when I use:
```
  - type: entity-filter
    entities:
      - light.bed_light
      - light.ceiling_lights
      - light.kitchen_lights
    state_filter:
      - "on"
    card:
      type: custom:fold-entity-row
      head:
        type: section
        label: Lit lamps
```
Entities shows up but without a card holder.
