### ISSUE TITLE
Row doesn't always 'unfold' - about 50% of the time it doesn't show the internal entities

### ISSUE THREAD

**Issue by mastakebob** [thomasloven/lovelace-fold-entity-row#240]
My Home Assistant version: 2023.7.1

Fold-entity-row version (FROM BROWSER CONSOLE):  v2.3 (from HACS)

What I am doing:  I've created 2 fold entity rows in an Entities card consisting of fans.  Intent is to have my 3 ceiling fans and 1 oscillating fan hidden from view until I click either of their rows to 'expand' it and show the individual fan entities.  

What I expected to happen:  The row expands to show my 3 fan entities.  

What happened instead:  About 50% of the time, the row doesn't expand.  The little carrot flips up to show that it should be expanded, but none of my fan entities are displayed.  ~50% of the time it does work (the row expands and I can see my fan entities).  See https://imgur.com/a/WFEWQJI for two images: first is it not working, second image is it working.  

**Minimal** steps to reproduce:
1) Create an entities card and add in the folding-entity-row yaml.  
2) Click the row and cross your fingers that it works as expected.  

```yaml
# The least amount of code possible to reproduce my error
type: entities
entities:
  - type: custom:fold-entity-row
    group_config:
      toggle: true
      type: custom:slider-entity-row
    head:
      type: section
      label: Ceiling Fans
    entities:
      - entity: fan.living_room
        name: Living Room
      - entity: fan.master_bedroom
        name: Main Bedroom
      - entity: fan.guest_bedroom
        name: Guest Bedroom
  - type: custom:fold-entity-row
    head:
      type: section
      label: Basement Fan
    entities:
      - entity: switch.fan_oscillating_smart_plug
        name: Basement Oscillating Fan
show_header_toggle: true
title: Fans
icon: mdi:fan

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
