### ISSUE TITLE
Allow head icon

### ISSUE THREAD

**Issue by jvcsw** [thomasloven/lovelace-fold-entity-row#241]
Hi and thank you for this integration.

My question and request is: Could I put an icon in the header without set an entity?

For exemple:

```
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      icon: mdi:bed-outline
      label: Suite
```

![imagen](https://github.com/thomasloven/lovelace-fold-entity-row/assets/37216513/4603379a-9770-406d-b456-8cb07f5a58b0)

Thanks again.
