### ISSUE TITLE
Solution: hide the spurious section divider

### ISSUE THREAD

**Issue by JonSilver** [thomasloven/lovelace-fold-entity-row#242]
I didn't find a solution to hiding that spurious top section divider, so I experimented with **card-mod** until I found out how to do it, and I thought I'd post the solution here just in case it helps someone.

Seems simple, but apparently can take ages to work it out.

```yaml
    card:
      type: custom:fold-entity-row
      head:
        type: section
        label: Section Without Divider
        card_mod:
          style: |
            .divider {
              display: none;
            }
```

Yes, it's really nothing to do with `fold-entity-row`, it's more to do with how the HA section css works. But it's been asked here, because evidently it becomes more of an issue when using an entities section as a folding header.

@thomasloven I hope you don't mind me leaving this here.
