### ISSUE TITLE
Empty space above the title

### ISSUE THREAD

**Issue by 1mfaasj** [thomasloven/lovelace-fold-entity-row#243]
My Home Assistant version: 2023.11.0

Fold-entity-row version: the latest version

**What I am doing:** I'm not sure if this is a bug but when I've got a template like this it shows a empty space above the title.
Is this something that I can disable or remove? I only want to show my title nothing more.
![image](https://github.com/thomasloven/lovelace-fold-entity-row/assets/71582854/3b695393-7aef-4663-8d2b-f7b81bca3ffb)

**What I expected to happen:** No empty space.

**What happened instead:** the empty space.

**Minimal** steps to reproduce:

```yaml
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      type: section
      label: Test
    group_config:
      secondary_info: last-changed
    entities:
      switch.wasmachine
# End of code
```
