### ISSUE TITLE
Allow header row to display entity attribute instead of sensor value

### ISSUE THREAD

**Issue by chriswood1001** [thomasloven/lovelace-fold-entity-row#247]
Allow the head entity to display an attribute instead of the normal value.

This is possible using the Entities card with 'attribute: name' and would be amazing if also made possible with this fold-entity-row.

Suggested addition:
```
type: custom:fold-entity-row
head:
  entity: sensor.server_disk_utalization
  name: Disk usage
  attribute: Percentage <-- new capability to display this as the header row value
entities:
  - entity: sensor.server_temperature
  - entity: sensor.server_fan_speed
```
