### ISSUE TITLE
Fold Entity Rows don't show Header Labels any more.

### ISSUE THREAD

**Issue by SdeGeata** [thomasloven/lovelace-fold-entity-row#250]
My Home Assistant version: 2021.XX.X

Core: 2024.6.1
Supervisor: 2024.10.2
Operating System: 13.1
Frontend: 20240605.0

Fold-entity-row version (FROM BROWSER CONSOLE):

2.2.0

What I am doing:

Custom: fold-entity-row works as expected, other than header labels no longer show. This worked in the past, so i am not sure what changed.

What I expected to happen:

Sections should display labels.

What happened instead:

Nothing showed.

**Minimal** steps to reproduce:

```yaml

type: entities
entities:
  - type: custom:fold-entity-row
    head:
      type: section
      label: open
    open: true
    entities:
      - light.kitchen
      - light.kitchen_sink_light
      - light.bathroom

# End of code
```

As taken from your examples, changed entities.
What is looks like:

![Screen Shot 2024-10-24 at 11 03 23 AM](https://github.com/user-attachments/assets/99749603-0b1e-475d-bc64-3034162a80dd)

What it should look like:

![Screen Shot 2024-10-24 at 11 05 17 AM](https://github.com/user-attachments/assets/0300690c-be1b-4f4f-8548-a9f00185d09a)

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by ildar170975** [comment]
2024.10.2, 2.2.0
Works here:
```
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      type: section
      label: xxxxx
    open: true
    entities:
      - sun.sun
      - sun.sun
```
![image](https://github.com/user-attachments/assets/d354cfba-8dc2-4841-a36f-550bc1ac769c)
