### ISSUE TITLE
Custom:fold-entity-row dash card does not show all entities in Companion App

### ISSUE THREAD

**Issue by RobusX** [thomasloven/lovelace-fold-entity-row#251]
Home Assistant Android app version(s): 20241002.4

Android version(s): 14

Device model(s): Galaxy A34 5G

Home Assistant version: 2024.10.4

Last working Home Assistant release (if known): 2024.9.3

Fold-entity-row version (FROM BROWSER CONSOLE):   2.2.0

What I am doing: 
With the latest release of the Companion App, entities in the custom:fold-entity-row card are not displayed correctly (this issue was rejected in HA Companion issues section, with remark, that it should be resolved within this custom card code).
Many entities within custom:fold-entity-row card are often missing after pressing the drop-down symbol. This issue does not occur on the standalone PC (Laptop) dashboard connected to the Home Assistant server running on Windows 10.

What I expected to happen: When drop down pressed, all included entities should display, like in the past HA releases.

What happened instead: Only one (first entity displayed, or no entities, or only a few)

**Minimal** steps to reproduce: Install code below on the dashboard, open it with Companion app and observe how many entities displayed.
Card code which many times within Companion APP displays only first entity within custom:fold-entity-row (named "Out Lights Update OFF") or no entities at all after dropdown is pressed (look where custom:fold-entity-row with "Outside Lights" starts below):

```yaml
type: entities
title: ""
state_color: true
show_header_toggle: false
entities:
  - type: custom:multiple-entity-row
    entity: sensor.out_temp
    name: Out Temp
    secondary_info: last-changed
    entities:
      - entity: sensor.max_temp_out_daily
        name: Max
        styles:
          width: 45px
          margin-top: "-24px"
          margin-right: "-10px"
      - entity: sensor.min_temp_out_daily
        name: Min
        styles:
          width: 45px
          margin-top: "-24px"
          margin-left: 30px
  - type: custom:multiple-entity-row
    entity: sensor.out_meter1_2670_humidity
    name: Out Hum
    secondary_info: last-changed
    entities:
      - entity: sensor.max_hum_out_daily
        name: Max
        styles:
          width: 45px
          margin-top: "-24px"
          margin-right: "-10px"
      - entity: sensor.min_hum_out_daily
        name: Min
        styles:
          width: 45px
          margin-top: "-24px"
          margin-left: 30px
  - type: custom:multiple-entity-row
    entity: binary_sensor.aqara_motion_sensor_balcony_occupancy
    name: Motion Sensor Balcony
    icon: mdi:motion-sensor
    secondary_info: last-changed
  - type: custom:fold-entity-row
    head:
      entity: light.pir_outside_lights
      name: Outside Lights
      state_color: true
      toggle: true
    entities:
      - type: custom:template-entity-row
        entity: input_boolean.lights_pir_out_update_off
        name: Out Lights Update OFF
        toggle: true
      - type: custom:template-entity-row
        entity: light.2pmstaircase_out
        icon: mdi:lightbulb
        name: PIR Staircase Out
        toggle: true
        secondary: |
          Power: {{ states('sensor.2pmstaircase_out_power') }} W
      - type: custom:template-entity-row
        entity: light.2pm_gar_out
        icon: mdi:lightbulb
        name: PIR Garage Out
        toggle: true
        secondary: |
          Power: {{ states('sensor.2pm_gar_out_power') }} W
      - type: custom:template-entity-row
        entity: light.pir_balcony
        icon: mdi:lightbulb
        name: PIR Balcony
        toggle: true
        secondary: |
          Power: {{ states('sensor.pir_balcony_power') }} W
      - type: custom:template-entity-row
        entity: light.2pm_balcony_left
        icon: mdi:lightbulb
        name: PIR Balcony Left
        toggle: true
        secondary: |
          Power: {{ states('sensor.2pm_balcony_left_power') }} W
      - type: custom:template-entity-row
        entity: light.2pm_balcony_right
        icon: mdi:lightbulb
        name: PIR Balcony Right
        toggle: true
        secondary: |
          Power: {{ states('sensor.2pm_balcony_right_power') }} W


Similar issue which appears many times within Companion App in this card code for another room (only a few entities within custom:fold-entitiy row displayed):

type: entities
title: " "
show_header_toggle: false
state_color: true
entities:
  - entity: sensor.meter_plus_0e1d_temperature
    type: custom:multiple-entity-row
    name: BedRoom
    show_state: false
    secondary_info: last-changed
    entities:
      - entity: sensor.meter_plus_0e1d_temperature
        name: Temp
        styles:
          margin-top: 0px
          margin-right: 40px
      - entity: sensor.meter_plus_0e1d_humidity
        name: Hum
        styles:
          margin-top: 0px
          margin-right: 0px
  - type: custom:fold-entity-row
    head:
      entity: input_boolean.bedroom_light_dash_state
      name: Bedroom
      toggle: true
      state_color: true
      style: |
        :host {
          --card-mod-icon-color: 
          {% if is_state(config.entity, 'on') %}
            yellow
          {% elif is_state('light.shelly_color_bedroom', 'on') or is_state('switch.plug_s_dehumidifier2', 'on')%}
            orange
          {% else %}
            grey
          {% endif %};
        }
    entities:
      - entity: binary_sensor.philips_bedroom_huemotion_occupancy
        name: Motion Sensor Hue
        icon: mdi:motion-sensor
        secondary_info: last-changed
      - entity: binary_sensor.aqara_motion_sensor_bedroom_strong_light_occupancy
        name: Motion Sensor Aqara
        icon: mdi:motion-sensor
        secondary_info: last-changed
      - type: custom:template-entity-row
        entity: light.shelly_color_bedroom
        icon: mdi:lightbulb
        name: Light Bedroom
        toggle: true
        secondary: |
          Power: {{ states('sensor.shelly_color_bedroom_power') }} W
      - type: custom:template-entity-row
        entity: switch.plug_s_dehumidifier2
        icon: mdi:power-socket-eu
        name: Dehumidifier2
        toggle: true
        secondary: |
          Power: {{ states('sensor.plug_s_dehumidifier2_power') }} W
      - entity: fan.air_purifier_92
        type: custom:multiple-entity-row
        toggle: true
        icon: mdi:air-purifier
        name: Air Purifier 92
        entities:
          - entity: sensor.air_purifier_92_pm2_5
            name: PM2.5
            styles:
              width: 80px
              margin-top: 0px
              margin-right: 0px
      - type: custom:template-entity-row
        entity: input_number.light_dashboard_on_delay
        name: Light ON Delay
        secondary: >
          Remaining Time: {{ states('sensor.bedroom_light_time_remaining') }}
          min


```
There are also other custom:fold entitiy row cards for other rooms, with similar issue.
The problem is not consistently repeatable. When the Home Assistant Companion App is closed and reopened, the issue with missing fold-entity-row items often persists. However, if the app is opened again after a few minutes or hours, all fold entities are sometimes displayed correctly (if lucky).

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/). 
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
