### ISSUE TITLE
Stopped working after home assistant version above 2025.6.0

### ISSUE THREAD

**Issue by arkady2k** [thomasloven/lovelace-fold-entity-row#252]
My Home Assistant version: 2025.6.1

Fold-entity-row version (FROM BROWSER CONSOLE): 2.2.0

What I am doing: after upgrading from 2025.5.3 I can not see anything on my page after foldable entities.

What I expected to happen: I was expecting to see my page

What happened instead:  I got last entity before foldable configurations kicked in

**Minimal** steps to reproduce: upgrade to version 2025.6.0 or 2025.6.1 

```yaml
# The least amount of code possible to reproduce my error

type: custom:expander-card
gap: 0.1em
padding: 0.1em
clear: false
title: "Control switches "
overlay-margin: 2em
child-padding: 0.5em
button-background: transparent
cards:
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: input_boolean.turn_of_acs
          - entity: automation.too_early_to_watch_cartoons
          - entity: input_boolean.run_school_mornings
          - entity: automation.turn_off_tv_after_15_min_between_9am_and_9_30pm
          - entity: input_boolean.keep_tv_off
          - entity: switch.living_room_tv
          - entity: media_player.living_room_tv
          - entity: media_player.home_theater_2
          - entity: input_boolean.automate_when_linda_home
          - entity: sensor.living_room_tv_media_input_source
            name: Living Room TV Input
          - entity: switch.sonoff_10015dac6f
          - entity: button.dell_xps_11_lock
visibility:
  - condition: user
    users:
      - f59ba4d03662466588b2229d656f31c9
      - 9802999d1967417bba19898be9e98148

# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
