### ISSUE TITLE
multiple-raw in fold-entity-raw

### ISSUE THREAD

**Issue by JBa-5176** [thomasloven/lovelace-fold-entity-row#253]
Hello, is it possible to insert "multiple-entity-row" from Benct (https://github.com/benct) into your "fold" map to display a list of entities with multiple values ​​on a single line and to reduce this list?
Thanks

**Comment by thomasloven** [comment]
You forgot to show what you have tried.

**Comment by jeremypsl** [comment]
I already use these together without any problem.

**Comment by mikosoft83** [comment]
It works like this for me:

```
type: entities
entities:
  - type: custom:fold-entity-row
    head:
      entity: binary_sensor.living_room_occupancy_group
      name: Occupancy
    entities:
      - type: custom:multiple-entity-row
        entity: binary_sensor.living_room_occupancy_occupancy
        name: Sensors
        icon: hass:motion-sensor
        show_state: false
        entities:
          - entity: binary_sensor.living_room_occupancy_occupancy
            name: Main
          - entity: binary_sensor.living_room_door_motion_iaszone
            name: Door
```
