### ISSUE TITLE
intermittent need to open the fold twice

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#255]
My Home Assistant version: 2025.6.1

Fold-entity-row version (FROM BROWSER CONSOLE):
2.3.1

What I am doing:
folding away charts, maps, logbook etc etc

What I expected to happen:
only a single click to open

What happened instead:

with certain fold contents, a single open is not showing the content of the fold, then a close and an open click again are needed to show the content alright

after that the fold behaves as designed, always showing the content

seems to happen with maps, cameras (like in this screen capture), logbook card
does not happen on individual listed entities

![Image](https://github.com/user-attachments/assets/8d24e2a6-f984-4d0f-b939-676a95dbde6d)

**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error
  - type: custom:fold-entity-row
    head:
      type: section
      label: Knmi
      card_mod: !include /config/dashboard/card_mods/label.yaml
#     padding: 0
    entities:
      - type: custom:hui-element
        card_type: picture
        image: https://cdn.knmi.nl/knmi/map/general/weather-map.gif
        tap_action: none
        hold_action:
          action: url
          url_path: https://www.knmi.nl/nederland-nu/weer/verwachtingen
# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
