### ISSUE TITLE
Pass Optionals to Items

### ISSUE THREAD

**Issue by zerox1212** [thomasloven/lovelace-fold-entity-row#30]
Add the ability to override the name field on the items.

```yaml
           items:
              - input_number.climate_sys_heating_target_home
                  name: Heat
```

The reason is that when using sliders with descriptive friendly names they don't fit in the entity row. Being able to over ride the name lets you fit the text without having 30 items named "Light".
