### ISSUE TITLE
Entities in fold-entity-row sections appear in the unused entities view

### ISSUE THREAD

**Issue by derandiunddasbo** [thomasloven/lovelace-fold-entity-row#32]
Entities that are only used inside fold-entity-row sections appear in HA's unused entities view. This is no showstopper for me. But unfortunately it makes the unused entities view quite useless.

It's hard to say, if this is an issue that should be fixed in lovelace (core) or if it should, respectively can be fixed in the fold-entity-row card.

```
entities:
  - head:
      label: Fenster
      type: section
    items:
      - sensor.dg_bad_fenster_status
    type: 'custom:fold-entity-row'
```
I'm using HA version 0.87.0.
