### ISSUE TITLE
Sensor style section head.

### ISSUE THREAD

**Issue by jazzyisj** [thomasloven/lovelace-fold-entity-row#40]
Would it be possible to add an additional type of heading for the fold entity row that could mimic the style of an entity, including an icon?    The "section" style does not work for me in most places I use the fold entity (and there are many of them!).  

What I end up having to do is create a "placeholder" sensor with a blank value to use as a section head for many of my fold entity items.  It would be much more convenient be able to specify it in the lovelace configuration.

```
- type: custom:fold-entity-row
    head: 
        type: sensor <--  made this up
        label: Wake Times
        icon: mdi:clock <-- made this up
```

This screenshot shows what I mean.  Wake Times is a section type, Bed Times is a placeholder sensor I had to create.

![image](https://user-images.githubusercontent.com/44064559/55637507-37d49b00-5793-11e9-8faf-54590d2aa523.png)

If not possible, no sweat, it is just a thought.  The workaround works just fine.  It just creates more work and unnecessary entities in the back end.
