### ISSUE TITLE
current value of slider sometimes disappears

### ISSUE THREAD

**Issue by GatoPharaoh** [thomasloven/lovelace-fold-entity-row#42]
I'm not entirely sure if this is a bug with fold-entity-row or lovelace itself

sometimes when the sidebar is visible, slider values as pictured below disappear. I will have to close the sidebar and reload the page to have them appear again. Sometimes they will reappear. It does look like it has something to do with the screen resolution.

![grafik](https://user-images.githubusercontent.com/12106737/56160759-4ce9cf00-5fc8-11e9-9951-44baf5aae6ef.png)

![grafik](https://user-images.githubusercontent.com/12106737/56160593-df3da300-5fc7-11e9-9aee-b891e2a94cc8.png)

any ideas?
thanks in advance

**Comment by kajo204** [comment]
I don't have any resolutions for this. but how did you get sliders in the fold? What does your yaml config look like?

**Comment by jawilson** [comment]
I have the same issue with this within a `vertical-stack`:
```yaml
              - type: custom:fold-entity-row
                head:
                  type: section
                  label: Control
                items:
                  - switch.apartment_home
                  - switch.apartment_fan
                  - entity: input_number.default_high_temp
                    name: High
                  - entity: input_number.default_low_temp
                    name: Low
```

The input numbers _never_ show their current numeral value:
<img src="https://user-images.githubusercontent.com/1368827/58438515-3b064c00-809d-11e9-981b-3656ed89e8b2.png" width="400" />

**Comment by GatoPharaoh** [comment]
@kajo204 i just created a group and with all the things i want inside the fold and put that into lovelace
```
         - type: entities
           title: Val 1
           show_header_toggle: false
           entities:
               - head: 
                   type: custom:dummy-entity-row
                   entity: group.one
                   icon: mdi:empty
                 type: custom:fold-entity-row
                 show_header_toggle: false
               - head: 
                   type: custom:dummy-entity-row
                   entity: group.two
                   icon: mdi:calendar
                 type: custom:fold-entity-row
                 show_header_toggle: false
               - head: 
                   type: custom:dummy-entity-row
                   entity: group.three
                   icon: mdi:clock-outline
                 type: custom:fold-entity-row
                 show_header_toggle: true
```
