### ISSUE TITLE
Stays open

### ISSUE THREAD

**Issue by PierreScerri** [thomasloven/lovelace-fold-entity-row#43]
Fold-entity-row stays open when coming back from another tab.

```
entities:
  - group_config:
      secondary_info: last-changed
    head: cover.bedroom_shutters
    open: false
    items:
      - type: divider
      - entity: cover.master_bedroom_shutter
      - entity: cover.master_bedroom_shutter
        full_row: true
        type: 'custom:slider-entity-row'
      - entity: cover.front_bedroom_shutter
      - entity: cover.front_bedroom_shutter
        full_row: true
        type: 'custom:slider-entity-row'
      - entity: cover.back_bedroom_shutter
      - entity: cover.back_bedroom_shutter
        full_row: true
        type: 'custom:slider-entity-row'
    type: 'custom:fold-entity-row'
show_header_toggle: false
title: Bedrooms
type: entities

```
