### ISSUE TITLE
Disable default 'entities' card click action on fold-entity-row head

### ISSUE THREAD

**Issue by ezet** [thomasloven/lovelace-fold-entity-row#50]
In order for the `entities` head toggle to function, I have to add `entity: <id>`  as a root property on the `fold-entity-row`, but this also causes any clicks on the expand/collapse button to trigger the default `more-info` click action.

Any way to disable this default click action on the root `entities` card?
```
entities:
  - type: 'custom:fold-entity-row'
    entity: light.kitchen_ceiling # **ISSUE**: this allows the entities header toggle to function, but causes annoying on-click actions when expanding/collapsing the row.
    head:
      type: 'custom:slider-entity-row'
      toggle: true
      name: Tak
      entity: light.kitchen_ceiling
    items:
      - entity: light.kitchen_1
        type: 'custom:slider-entity-row'
        toggle: true
        name: 1
      - entity: light.kitchen_2
        type: 'custom:slider-entity-row'
        toggle: true
        name: 2
      - entity: light.kitchen_3
        toggle: true
        name: 3
        type: 'custom:slider-entity-row'
 ```
