### ISSUE TITLE
Fold closes automatically when input numbers are changed

### ISSUE THREAD

**Issue by tomlut** [thomasloven/lovelace-fold-entity-row#54]
My Home Assistant version: 0.XX.X
0.94.4

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Unfold a row, adjust an input number (slider). 

What I expected to happen:
Unfold a row, adjust an input number (slider). The fold stays open so I can adjust another entity.

What happened instead:
Unfold a row, adjust an input number (slider). The fold closes automatically.
This is specific to input numbers. The fold does not close automatically if I adjust other controls like input booleans, input date-times, toggle switches or even custom:slider-entity-rows.
**Minimal** steps to reproduce:
As above.

```yaml
# The least ammount of code possible to reproduce my error

entities:
  - head:
      label: Automation
      type: section
    items:
      - input_boolean.dining_workday
      - input_datetime.dining_am_on_time
      - input_number.dining_heat_temp_set
    padding: 0
    type: 'custom:fold-entity-row'
show_header_toggle: false
type: entities


# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
