### ISSUE TITLE
Toggle switch gets cut off on mobile

### ISSUE THREAD

**Issue by skynet01** [thomasloven/lovelace-fold-entity-row#55]
**My Home Assistant version: 0.95.4**
My lovelace configuration method (GUI or yaml):
Yaml
**What I am doing:**
resizing the browser or using a phone 

**What I expected to happen:**
toggles and expand control to show up

**What happened instead:**
it doesn't show up on mobile or small resolutions
video: https://secure.fabriceleven.com/QfLaxf

**Minimal** steps to reproduce:
Enable slider+toggle then resize the browser

```yaml
# The least ammount of code possible to reproduce my error

- head:
      entity: light.master_bedroom_dimmer
      name: Bedroom
      toggle: true
      type: 'custom:slider-entity-row'
    items:
      - entity: light.master_vanessa
        toggle: true
        type: 'custom:slider-entity-row'
      - entity: light.master_alex
        toggle: true
        type: 'custom:slider-entity-row'
    type: 'custom:fold-entity-row'


# End of code
```

**Error messages from the browser console:**
none

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
