### ISSUE TITLE
Date picker for input_datetime doesn't work in folded entity

### ISSUE THREAD

**Issue by vamichael** [thomasloven/lovelace-fold-entity-row#57]
I just implemented fold-entity-row, and the when you click on a input_datetime entity, the pop-calendar doesn't appear:

This is my original yaml, where the date picker works:

```
entities:
  - entity: input_text.front_door_name_2
  - entity: input_text.front_door_code_2
  - entity: input_boolean.front_door_enabled_2
  - entity: input_boolean.front_door_notify_2
  - type: divider
  - entity: binary_sensor.front_door_active_2
  - type: divider
  - entity: input_boolean.front_door_daterange_2
  - entity: input_datetime.start_date_2
  - entity: input_datetime.end_date_2
show_header_toggle: false
title: Slot 2
type: entities
```

and this is my modified code where the date picker stops working: 

```
entities:
  - entity: input_text.front_door_name_1
  - entity: input_text.front_door_code_1
  - entity: input_boolean.front_door_enabled_1
  - entity: input_boolean.front_door_notify_1
  - type: divider
  - entity: binary_sensor.front_door_active_1
  - type: 'custom:fold-entity-row'
    head:
      type: section
      label: Access Options
    open: false
    entities:
      - entity: input_boolean.front_door_daterange_1
      - entity: input_datetime.start_date_1
      - entity: input_datetime.end_date_1
  - type: divider
show_header_toggle: false
title: Slot 1
type: entities

```
