### ISSUE TITLE
Input_number entity is missing number value after the slider

### ISSUE THREAD

**Issue by gtdiehl** [thomasloven/lovelace-fold-entity-row#58]
My Home Assistant version: 0.95.0

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
Created a card with a list of input_number entities using the `custom:fold-entity-row` inside an `entities` card

What I expected to happen:
Expected four attributes to be shown:
- Icon
- Name
- Slider
- Value

What happened instead:
Only three attributes were displayed, `Value` from the above list was missing

**Minimal** steps to reproduce:

```yaml
            - type: entities
              entities:
                - type: custom:fold-entity-row
                  head:
                    type: section
                    label: Program 1 Run Times
                  open: true
                  entities:
                    -  input_number.sprinkler_program1_station1_run_time
                    -  input_number.sprinkler_program1_station2_run_time
```

Error messages from the browser console:
I noticed when I the Developer Tools in Chrome that the HTML code does have the state value of the slider, but it has an empty `hidden` property, and removing `hidden` property resolves the problem but only until the page is refreshed:
```
<div class="flex">
  <ha-slider pin="" ignore-bar-touch="" id="input" dir="ltr" role="slider" tabindex="0" 
  value="8" aria-valuemin="0" aria-valuemax="30" aria-valuenow="8" aria-disabled="false"> 
 </ha-slider>
 <span class="state" hidden="">8</span>
</div>
```

Whereas when I use the `input_number` entity inside an `entities` card without using the `custom:fold-entity-row` the state value is shown at the right side of the slider.

Can the `hidden` propertty be removed when rendering the card?

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[x] Have made sure I am using the latest version of the plugin.

[x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by thomasloven** [comment]
That's not fold-entity-row. That's Home Assistant. It hides the value when there's not enough room.
You could try changing the padding to give it more room.

**Comment by gtdiehl** [comment]
I tried adding some padding without any luck.  Changing my yaml from what I originally posted to this:
```
              - type: entities
                title: Program 1 Run Times
                entities:
                  -  input_number.sprinkler_program1_station1_run_time
                  -  input_number.sprinkler_program1_station2_run_time
```

I can see the values at the right of the slider.

**Comment by thomasloven** [comment]
So not even:

```yaml
            - type: entities
              entities:
                - type: custom:fold-entity-row
                  padding: 0
                  head:
                    type: section
                    label: Program 1 Run Times
                  open: true
                  entities:
                    -  input_number.sprinkler_program1_station1_run_time
                    -  input_number.sprinkler_program1_station2_run_time
```
works?
