### ISSUE TITLE
Add the ability to set a type when the head is a group

### ISSUE THREAD

**Issue by pmontgo33** [thomasloven/lovelace-fold-entity-row#59]
I think it would be nice to have the ability to add a type to the head when you want it to be a group:

```
- type: custom:fold-entity-row
  head:
    type: custom:toggle-lock-entity-row
    entity: group.all_automations
```
This would make the switch on the head contain your lock icon. Another option that would be helpful would be the ability to remove the switch altogether from the head when its a group like this:

```
- type: custom:fold-entity-row
  head:
    entity: group.all_automations
    show_header_toggle: false
```
