### ISSUE TITLE
Dimmer value disappears

### ISSUE THREAD

**Issue by gerard33** [thomasloven/lovelace-fold-entity-row#6]
The dimmer value dissappears behind the row above. This also applies for the other rows, so the value is not only disappearing after the header row.

![screenshot_1](https://user-images.githubusercontent.com/11230573/47048579-1c50e600-d19b-11e8-9390-fb8c2c465e8c.jpg)

```yaml
- type: entities
  entities:
  - type: custom:fold-entity-row
      head:
        entity: group.lampen_kamer
        type: custom:toggle-lock-entity-row
      group_config:
        type: custom:slider-entity-row
        hide_when_off: true
```
