### ISSUE TITLE
when using a slider, it will pop up a slider dialog after setting the value

### ISSUE THREAD

**Issue by pdwonline** [thomasloven/lovelace-fold-entity-row#62]
Using the latest greatest HA version on a NUC. 

I am a huge fan of the lovelance-fold-entity-row. It keeps my cards clean and neat. However, when I place a slider on a fold-entity, it has some unwanted behaviour:  The slider can be set from the unfold row, but when I am done and relase te mouse button on the slider entity, a popup appears where I can set the slider. (what I have just done). Another entities such as a input_select, it works normally.

This is my card config:
```

entities:
  - head: switch.living_lights
    items:
      - light.staande_lamp
      - light.fibaro_system_fgd212_dimmer_level
      - light.schemerlamp
      - switch.shenzhen_neo_electronics_co_ltd_power_plug_12a_switch
      - light.fibaro_system_fgd212_dimmer_2_level_3
      - light.sfeerlamp
      - head: null
        type: section
      - automation.kamerverlichting_auto_aan
      - sensor.neo_coolcam_v2_luminance_5
      - sensor.neo_coolcam_v2_luminance_6
    type: 'custom:fold-entity-row'
  - head: sensor.fibaro_system_fgsd002_smoke_sensor_temperature_4
    items:
      - input_number.toon_temperature
      - input_select.toon_preset
      - climate.toon_thermostaat
    type: 'custom:fold-entity-row'
  - head: variable.luxaflex_status
    items:
      - input_select.luxaflex_dining
      - input_select.luxaflex_living
      - automation.luxaflex_automaat
    type: 'custom:fold-entity-row'
  - head: binary_sensor.movement_living
    items:
      - binary_sensor.neo_coolcam_sensor_v2_5
      - binary_sensor.neo_coolcam_sensor_v2_6
    type: 'custom:fold-entity-row'
id: 66
show_header_toggle: false
title: Woonkamer
type: entities
```

Or is there an option to enable / disable the popup?
