### ISSUE TITLE
Memory leak when displaying sensor values

### ISSUE THREAD

**Issue by ultratoto14** [thomasloven/lovelace-fold-entity-row#63]
My Home Assistant version: 0.97.2

My lovelace configuration method (GUI or yaml): GUI

What I am doing: i have a normal entity card showing my download/upload bandwidth and I use fold entity row card to show details about the 3 most uploader and downloader devices.

What I expected to happen: memory taken should be almost stable

What happened instead: browser memory of HA tab is constantly growing

**Minimal** steps to reproduce: 

``` yaml
# This is working:
entities:
  - entity: sensor.internet_speed_in
  - entity: sensor.internet_speed_out
  - filter:
      include:
        - key: sensor.biggest_downloader.ip
        - key: sensor.biggest_downloader.throughput
        - key: sensor.second_downloader.ip
        - key: sensor.second_downloader.throughput
        - key: sensor.third_downloader.ip
        - key: sensor.third_downloader.throughput
    heading_name: Downloaders
    heading_state: States
    type: 'custom:entity-attributes-card'
  - filter:
      include:
        - key: sensor.biggest_uploader.ip
        - key: sensor.biggest_uploader.throughput
        - key: sensor.second_uploader.ip
        - key: sensor.second_uploader.throughput
        - key: sensor.third_uploader.ip
        - key: sensor.third_uploader.throughput
    heading_name: Uploaders
    heading_state: States
    type: 'custom:entity-attributes-card'
show_header_toggle: false
title: Bandwidth
type: entities
# End of code
```

``` yaml
# This is not working 
entities:
  - entity: sensor.internet_speed_in
  - entity: sensor.internet_speed_out
  - head:
      label: Détails
      type: section
    items:
      - filter:
          include:
            - key: sensor.biggest_downloader.ip
            - key: sensor.biggest_downloader.throughput
            - key: sensor.second_downloader.ip
            - key: sensor.second_downloader.throughput
            - key: sensor.third_downloader.ip
            - key: sensor.third_downloader.throughput
        heading_name: Downloaders
        heading_state: States
        type: 'custom:entity-attributes-card'
      - filter:
          include:
            - key: sensor.biggest_uploader.ip
            - key: sensor.biggest_uploader.throughput
            - key: sensor.second_uploader.ip
            - key: sensor.second_uploader.throughput
            - key: sensor.third_uploader.ip
            - key: sensor.third_uploader.throughput
        heading_name: Uploaders
        heading_state: States
        type: 'custom:entity-attributes-card'
    type: 'custom:fold-entity-row'
show_header_toggle: false
title: Bandwidth
# End of code
```

Error messages from the browser console: none

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[X] Have made sure I am using the latest version of the plugin.

[X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
