### ISSUE TITLE
The show_header_toggle of entities is not working

### ISSUE THREAD

**Issue by lbouriez** [thomasloven/lovelace-fold-entity-row#64]
My Home Assistant version: 0.99.2

My lovelace configuration method (GUI or yaml): yaml

With the entitie below, when I click on the toggle button of the card, only the basic entities are turned on/off. The one from the fold component are not toggled.

**Minimal** steps to reproduce:
```
- type: entities
                title: 'Lights'
                show_header_toggle: true
                entities:
                    - light.balcony_group
                    - light.bathroom_group
                    - type: custom:fold-entity-row
                      head: light.bedroom_group
                      entities:
                        - light.giulia_night_table
                        - light.laurent_night_table
                        - light.bedroom_2
                        - light.bedroom_1
                        - light.bedroom_led
                        - switch.sonoff_100048cb54
```

```yaml
# The least ammount of code possible to reproduce my error



# End of code
```

Error messages from the browser console:

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

[ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

[ ] Have made sure I am using the latest version of the plugin.

[ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

[ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
