### ISSUE TITLE
Display scrollbars only when required

### ISSUE THREAD

**Issue by clabnet** [thomasloven/lovelace-fold-entity-row#68]
My Home Assistant version: 0.100.3

My lovelace configuration method (GUI or yaml): yaml

What I am doing:
Add fold-entity-row to collapse list of person

What I expected to happen:
Add the scrollbars to the browser's main page **only when required**
[See image here :](https://pasteboard.co/IDA5Wdf.png)

What happened instead:
The horizontals and vertical scrollbars appears when I insert the fold-entity-group card.
The problem arise only when insert this type of card.

```yaml
    - type: vertical-stack    
        cards:
          - type: horizontal-stack
            cards:
            - type: custom:auto-entities
              card:
                type: custom:fold-entity-row
                head:
                  type: section
                  label: In sede
                open: true
                padding: 20
              filter:
                include:
                  - domain: person
                    state: "entrato"
                    options:
                      secondary_info: last-changed
```

Error messages from the browser console:
any message on console

---

Another little info, please : seeing the image above, how to padding to left the word "entrato" ? Tks

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin. 
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
