### ISSUE TITLE
Console error when using custom:fold-entity-row with custom:slider-entity-row

### ISSUE THREAD

**Issue by darkkatarsis** [thomasloven/lovelace-fold-entity-row#70]
My Home Assistant version: 0.101.1

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:

What I expected to happen:

What happened instead:

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
- entities:
          - type: custom:fold-entity-row
            head: light.all_living_room
            entities:
              - entity: light.living_room
              - entity: light.kitchen
              - entity: light.fibaro_system_fgd212_dimmer_2_level
                toggle: true
                type: 'custom:slider-entity-row'
        show_header_toggle: false
        type: entities


# End of code
```

Error messages from the browser console:
```
dumper.js:756 Uncaught (in promise) r {name: "YAMLException", reason: "unacceptable kind of an object to dump [object Undefined]", mark: undefined, message: "unacceptable kind of an object to dump [object Undefined]", stack: "YAMLException: unacceptable kind of an object to d…org:8123/frontend_latest/app.34e7b19f.js:2:12846)"}
```
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
