### ISSUE TITLE
Cast: Cannot read property 'hass' of null

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-fold-entity-row#75]
My Home Assistant version: 0.XX.X

103.5
My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
Casting a perfectly fine working card using fold-entity-row 

What I expected to happen:

the card showing nicely ;-)

What happened instead:

all red cards displaying:
```
Cannot read property 'hass' of null
```

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
  - type: entities
    title: Ikea light groups
    show_header_toggle: false
    entities:
      - type: custom:fold-entity-row
        head: group.hallway_lights
        group_config:
          secondary_info: last-changed
      - type: custom:fold-entity-row
        head: group.marte_lights
      - type: custom:fold-entity-row
        head: group.library_lights
        group_config:
          secondary_info: last-changed


# End of code
```

Error messages from the browser console:

None, as said card works fine in Lovelace
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [ ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [ ] Have made sure I am using the latest version of the plugin.
- [ ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [ ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
<img width="300" alt="Schermafbeelding 2020-01-10 om 10 55 56" src="https://user-images.githubusercontent.com/33354141/72143878-d089ee00-3397-11ea-8b0d-11c6948094c1.png">
