### ISSUE TITLE
Padding bottom on a collapsed fold-row entity is too large

### ISSUE THREAD

**Issue by marcelodavanzo** [thomasloven/lovelace-fold-entity-row#77]
My Home Assistant version: 0.103.6

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Adding a fold-row to the bottom of a card produces too large padding-bottom when fold-row is collapsed

What I expected to happen:
A reasonable amount of padding at the bottom of the card when closed

What happened instead:
Disproportionately large padding at the bottom of the card when fold-row it's collapsed. It looks fine when it's expanded.

![image](https://user-images.githubusercontent.com/8631786/72203799-8ae92600-3468-11ea-85a3-d52f8f009bb0.png)

**Minimal** steps to reproduce:
Add a collapsed fold-row as the bottom most element of a card

```yaml
# The least amount of code possible to reproduce my error

entities:
  - entities:
      - entity: light.bedroom_ceiling
        name: Bedroom Ceiling
      - entity: light.bedroom_strip
        name: Bedroom Strip
    head:
      entity: light.bedroom
      name: All lights
    type: 'custom:fold-entity-row'
  - entities:
      - entity: scene.bedroom_sleep
    head:
      label: Scenes
      type: section
    padding: 0
    type: 'custom:fold-entity-row'
show_header_toggle: false
theme: Backend-selected
title: "Bedroom"
type: entities

# End of code
```

Error messages from the browser console:
none

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [ x ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [ x ] Have made sure I am using the latest version of the plugin.
- [ x ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [ x ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
