### ISSUE TITLE
light group

### ISSUE THREAD

**Issue by folrewef** [thomasloven/lovelace-fold-entity-row#8]
Hi,

I tried to use the fold-entity-row with a light group. I get the arrow but nothing else. In my ui-lovelace.yaml I have (only tested on a light group - light.lampor_i_vardagsrummet - which consists of three lamps):

```
        cards:
          - type: entities
            title: Lampor
            show_header_toggle: false
            entities:
              - switch.matsal
              - type: custom:fold-entity-row
                head: light.lampor_i_vardagsrummet
              - light.lampor_i_matsalen
              - light.lampor_i_ovre_hall
              - light.hallampan
              - light.lampor_utomhus
```

![skarmavbild 2018-10-18 kl 11 48 18](https://user-images.githubusercontent.com/43371683/47146208-e2cbc800-d2cb-11e8-905c-a9946a09b731.png)

Is it supposed to work with light group. Even if I have to specify the separate lamps under the group, shouldn't the head be shown?
