### ISSUE TITLE
Option for toggle switch in header label to turn on/off all entities

### ISSUE THREAD

**Issue by gadgetchnnel** [thomasloven/lovelace-fold-entity-row#80]
With Home Assistant 0.104 removing the default group.all_* groups, so it is no longer possible to do this (unless you manually create the group):

```yaml
- type: 'custom:fold-entity-row'
   head: group.all_lights
```
The only alternative is something like this:

```yaml
- type: 'custom:auto-entities'
    filter:
      include:
        - domain: light
    card:
      type: 'custom:fold-entity-row'
      head:
        type: section
        label: Lights
```
Unfortunately, this means that there is no longer a toggle switch in the header which will turn on/off all the lights. Would it be possible to add an option for this?
