### ISSUE TITLE
type: section causes line to appear above row

### ISSUE THREAD

**Issue by benjgos** [thomasloven/lovelace-fold-entity-row#81]
Hi,
Love this plugin! it helps me avoid the super ugly use of input_booleans and conditional cards, and works incredibly with auto-entities. :)

When using type: section, a thin line shows up above the fold row. it's not a divider, it's more faint and goes entirely across the card.
Also, it doesn't seem to happen when using type: entity. (see image)

```yaml
      - type: entities
        entities:
          - sensor.family_room_hue_sensor_temperature
          - type: custom:fold-entity-row
            head:
              type: entity
              entity: binary_sensor.family_room_hue_sensor_motion
              secondary_info: last-changed
            entities:
              - sensor.family_room_hue_sensor_temperature
          - type: custom:fold-entity-row
            head:
              type: section
              label: "IR Control"
            entities:
              - entity: switch.ir_fr_samsung_tv_power_on_off
```
<img width="438" alt="screenshot_fold_entity" src="https://user-images.githubusercontent.com/232766/72969768-cd293600-3d8b-11ea-86f2-4eced81e2f18.png">

I can't tell if this is intentional as i couldn't find a mention of it in the docs. But if it is, is there a way to just have the fold row include only a title without the line (like the type: entity)?

Using Home Assistant 0.104.3 / Build 12 of fold-entity-row from HACS

Thank you for your work on this!
