### ISSUE TITLE
Does not work when horizontal/vertical-stack card  inside

### ISSUE THREAD

**Issue by Tom-ahawk** [thomasloven/lovelace-fold-entity-row#82]
My Home Assistant version: 0.104.3
My lovelace configuration method (GUI or yaml): GUI

I am not able to put the cards, horizontal-stack card or the vertical-stack card inside the lovelace-fold-entity-row card. Trying to get several rows with buttons (custom-button card), inside the fold-entity-row card.

![image](https://user-images.githubusercontent.com/35527507/73134672-ca536d00-4039-11ea-8380-f488b9bfe0db.png)

Using horizontal-stack card or the vertical-stack card  inside other cards like type: 'custom:swipe-card' works...
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35527507/73134746-6da48200-403a-11ea-8096-61aa3df4e394.gif)

**Comment by thomasloven** [comment]
> head: and any row in entities: can be customized in exactly the same ways as ordinary entities card rows.

How would you put a vertical-stack in an entities card?

**Comment by Tom-ahawk** [comment]
I am sorry, - not getting this right. Should this work?

```
type: 'custom:fold-entity-row'
head:
  type: section
  label: Test
entities:
  - type: horizontal-stack
    cards:
      - entity: light.led_strip1
        type: light
      - entity: light.led_strip2
        type: light
```
