### ISSUE TITLE
Right margin of entities

### ISSUE THREAD

**Issue by alegiovannelli** [thomasloven/lovelace-fold-entity-row#85]
My Home Assistant version: 0.105.1

My lovelace configuration method (GUI or yaml): GUI

What I expected to happen:
Possibility to set the margins of the entities, right and left, or that the margins are set automatically with a minimum of padding

What happened instead: When inserting entities group, the right part is represented without padding like image attached

![Senza titolo](https://user-images.githubusercontent.com/29068703/73976453-9f65f480-4928-11ea-8d76-106fbe9e7431.png)

**Comment by sstefanowski** [comment]
I have very similar issue with right padding. I'm using combination of 3 custom Lovelace plugins:

- fold-enity-row, 
- auto-entities,
- vertical-stack-in-card

and the right padding is incorrect. Can we have some parameter to control right padding?
![fold-row1](https://user-images.githubusercontent.com/36473471/80315707-9f73e300-87f9-11ea-929c-eb88785da2a4.png)


This is part of my config
```
title: PC Games
type: 'custom:vertical-stack-in-card'
cards:
  - type: entities
    entities:
      - device_tracker.pc_games

(...)

  - type: 'custom:auto-entities'
    card:
      type: 'custom:fold-entity-row'
      padding: 5
      head:
        type: section
        label: Disks
    filter:
      include:
        - name: '*PC-GAMES Storage*'
  - type: 'custom:auto-entities'
    card:
      type: 'custom:fold-entity-row'
      head:
        type: section
        label: Network
    filter:
      include:
        - name: '*PC-GAMES Network*'
```
