### ISSUE TITLE
t is undefined

### ISSUE THREAD

**Issue by stevegore** [thomasloven/lovelace-fold-entity-row#86]
My Home Assistant version: latest

My lovelace configuration method (GUI or yaml): Mainly yaml

What I am doing:
Attempting to get this working from fresh install. 
Using Firefox.

What I expected to happen:
No exception

What happened instead:
't is not defined' exception.

```yaml
resources:
  - type: module
    url: /community_plugin/custom-header/custom-header.js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js?v=1
    type: module
background: var(--background-image)
title: Home
views:
  - badges: null
    cards:
      - entities:
          - entity: light.lounge_room_1
            name: '1'
          - entity: light.lounge_room_2
            name: '2'
          - entity: light.lounge_room_3
            name: '3'
          - entity: light.left_side_lamp
          - entity: light.right_side_lamp
        show_header_toggle: true
        title: Lounge Room
        type: 'custom:fold-entity-row'
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  compact_mode: true
  button_text:
    options: ':'
```

Error messages from the browser console:

```
fold-entity-row TypeError: "t is undefined"
    setConfig fold-entity-row.js:1
    o create-element-base.ts:39
    a create-element-base.ts:79
    bn create-card-element.ts:57
    _createCard hui-card-preview.ts:71
    set config hui-card-preview.ts:52
    commit parts.ts:420
    commit parts.ts:133
    update template-instance.ts:53
    __commitTemplateResult parts.ts:277
    commit parts.ts:218
    update template-instance.ts:53
    __commitTemplateResult parts.ts:277
    commit parts.ts:218
    s render.ts:55
    render shady-render.ts:278
    update lit-element.ts:220
    performUpdate updating-element.ts:704
    _enqueueUpdate updating-element.ts:653
create-element-base.ts:42:12
    o create-element-base.ts:42
    a create-element-base.ts:79
    bn create-card-element.ts:57
    _createCard hui-card-preview.ts:71
    set config hui-card-preview.ts:52
    commit parts.ts:420
    commit parts.ts:133
    update template-instance.ts:53
    __commitTemplateResult parts.ts:277
    commit parts.ts:218
    update template-instance.ts:53
    __commitTemplateResult parts.ts:277
    commit parts.ts:218
    s render.ts:55
    render shady-render.ts:278
    update lit-element.ts:220
    performUpdate updating-element.ts:704
    _enqueueUpdate updating-element.ts:653

```
---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
