### ISSUE TITLE
lazy loaded rows not rendering

### ISSUE THREAD

**Issue by iantrich** [thomasloven/lovelace-fold-entity-row#91]
My Home Assistant version: 0.XX.X
0.107.0b3

My lovelace configuration method (GUI or yaml):
GUI

What I am doing:
Folding

What I expected to happen:
Fold them rows

What happened instead:
Custom element doesn't exist: hui-climate-entity-row.

**Minimal** steps to reproduce:
Use a lazy loaded row in fold-entity-row config

```yaml
# The least ammount of code possible to reproduce my error
type: entities
entities:
  - entities:
      - entity: climate.thermostat
    head:
      entity: climate.thermostat
    type: 'custom:fold-entity-row'
# End of code
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
