### ISSUE TITLE
Custom element doesn't exist: hui-section-row.

### ISSUE THREAD

**Issue by akiaie** [thomasloven/lovelace-fold-entity-row#98]
My Home Assistant version: 0.108.3

My lovelace configuration method (GUI or yaml):  yaml

What I am doing:
 trying to use the fold-entity-row but it gives me "Custom element doesn't exist: hui-section-row." message when I change the dead: 'entity name' to head: type and label

What I expected to happen:
fold entity doesn't accept the section type and label.

What happened instead:

![image](https://user-images.githubusercontent.com/39561169/79201275-62f3cf00-7e6a-11ea-863e-e33adad42a8b.png)

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error

`    cards:
      - type: entities
        entities:
          title: Lights
        #entities:
          - type: custom:fold-entity-row
            head:
              type: section
              label: Master Bedroom
            open: true
            entities:
              - light.master_bedroom_ceilings
              - light.bed_lamp
              - switch.wardrobe`


# End of code
```

Error messages from the browser console:
Custom element doesn't exist: hui-section-row.

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [X ] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X ] Have made sure I am using the latest version of the plugin.
- [X ] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X ] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
