### ISSUE TITLE
using a combination of auto-entities and fold-entity-row renders the card with transparent background

### ISSUE THREAD

**Issue by lolouk44** [thomasloven/lovelace-fold-entity-row#99]
My Home Assistant version: 0.108.4

My lovelace configuration method (GUI or yaml):
yaml

What I am doing:
using auto-entities and fold-entity-row together

What I expected to happen:
white (default) card background

What happened instead:
card background is transparent

**Minimal** steps to reproduce:

```yaml
# The least ammount of code possible to reproduce my error
cards:
  - type: custom:auto-entities
    card:
      type: custom:fold-entity-row
      head:
        type: section
        label: All Automations
      open: false
    filter:
      include:
        - entity_id: "automation.*"
    sort:
      method: 'name'
# End of code
```

Error messages from the browser console:
None

---

**By putting an X in the boxes ([ ]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [x] Have made sure I am using the latest version of the plugin.
- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.
